import { NPC } from "../../types";

export const CITY_NPCS: NPC[] = [
  // ══════════════════════════════════════════════════════════════
  // 1. TRANSPORTATION HUB
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_david",
    name: "David Sterling",
    age: 38,
    gender: "male",
    occupation: "Senior Airport Border & Customs Officer",
    districtId: "transportation",
    locationId: "loc_airport_arrival",
    locationName: "International Airport Terminal B",
    avatarEmoji: "👮‍♂️",
    avatarColor: "#3b82f6",
    personality: "Formal, authoritative yet helpful, highly observant, values clarity and honesty.",
    speakingStyle: "Clear standard British English, precise questions, structured instructions.",
    accent: "Neutral British RP",
    level: "A1",
    relationshipScore: 15,
    relationshipTier: "Acquaintance",
    memory: ["Checked passport upon arrival", "Provided directions to the Central Metro Station"],
    currentScheduleActivity: "Inspecting passport declarations at Border Gate 3",
    greetingText: "Good day. Welcome to English City. Passport and declaration form, please.",
    defaultTopics: ["Passport Control", "Luggage & Customs", "Getting to Downtown", "Currency Exchange"],
    voicePitch: 0.9,
    voiceRate: 0.9,
    voiceGender: "male",
    interests: ["International aviation", "Border security", "Crossword puzzles"],
    dislikes: ["Unclear documentation", "Rushing through checkpoints"],
    goals: ["Ensure smooth passenger transit through terminal security"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_airport_arrival",
    preferredHangouts: ["loc_subway_central", "loc_sarah_cafe"],
    currentMood: "strict",
    vocabularyObjectives: ["customs", "declaration", "purpose of visit", "duration", "citizenship"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 8,
        locationId: "loc_airport_arrival",
        roomName: "Airline Check-in & Bag Drop",
        activityDescription: "Briefing morning ground staff at Terminal B",
        arabicActivity: "تقديم التوجيهات الصباحية لطاقم المطار",
        dialogueTopic: "Terminal Security & Check-in",
      },
      {
        timeOfDay: "afternoon",
        hour: 14,
        locationId: "loc_airport_arrival",
        roomName: "Customs & Passport Control",
        activityDescription: "Inspecting international arrivals and passport declarations",
        arabicActivity: "فحص القادمين الدوليين وإقرارات الجوازات",
        dialogueTopic: "Customs Inspections & Declarations",
      },
      {
        timeOfDay: "evening",
        hour: 19,
        locationId: "loc_subway_central",
        roomName: "Automated Metro Fare Kiosks",
        activityDescription: "Commuting home via the Central Metro Express",
        arabicActivity: "العودة إلى المنزل عبر مترو الأنفاق المركزي",
        dialogueTopic: "City Transit Tips & Commute",
      },
    ],
  },
  {
    id: "npc_flight_agent_emma",
    name: "Emma Watson-Lee",
    age: 29,
    gender: "female",
    occupation: "Lead Airline Ticketing & Gate Agent",
    districtId: "transportation",
    locationId: "loc_airport_arrival",
    locationName: "International Airport Terminal B",
    avatarEmoji: "👩‍✈️",
    avatarColor: "#0284c7",
    personality: "Poised, calm under pressure, friendly, quick with gate logistics and boarding updates.",
    speakingStyle: "Crisp, polite customer-service English, articulates gate letters clearly.",
    accent: "Australian / International",
    level: "A1",
    relationshipScore: 10,
    relationshipTier: "Stranger",
    memory: [],
    currentScheduleActivity: "Assisting passengers with gate changes and seat upgrades",
    greetingText: "Hello there! Are you checking bags today or heading straight to boarding?",
    defaultTopics: ["Boarding Pass Issues", "Seat Assignment (Window vs Aisle)", "Baggage Allowance", "Flight Delay Status"],
    voicePitch: 1.0,
    voiceRate: 0.95,
    voiceGender: "female",
    interests: ["World travel", "Aviation history", "Scuba diving"],
    goals: ["Help every passenger reach their destination smoothly"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_airport_arrival",
    preferredHangouts: ["loc_transit_cafe", "loc_sunset_beach"],
    currentMood: "helpful",
    vocabularyObjectives: ["boarding pass", "aisle seat", "window seat", "overhead bin", "carry-on"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 7,
        locationId: "loc_airport_arrival",
        roomName: "Airline Check-in & Bag Drop",
        activityDescription: "Printing baggage tags and issuing boarding passes",
        arabicActivity: "طباعة بطاقات الأمتعة وإصدار بطاقات صعود الطائرة",
        dialogueTopic: "Seat Selection & Luggage Weight",
      },
    ],
  },
  {
    id: "npc_transit_agent_brian",
    name: "Brian O'Connor",
    age: 52,
    gender: "male",
    occupation: "Senior Subway Station Master",
    districtId: "transportation",
    locationId: "loc_subway_central",
    locationName: "Central Metro Grand Station",
    avatarEmoji: "🚇",
    avatarColor: "#2563eb",
    personality: "Warm, booming voice, patient, knows every subway connection by heart.",
    speakingStyle: "Irish lilt, friendly, uses practical transit terms.",
    accent: "Irish / Dublin",
    level: "A1",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: ["Helped you buy your first MetroCard"],
    currentScheduleActivity: "Assisting tourists with ticket vending machines",
    greetingText: "Top of the morning to you! Need a hand with the route map or topping up your transit card?",
    defaultTopics: ["MetroCard Reloads", "Transferring Between Lines", "Express vs Local Trains", "Lost & Found"],
    voicePitch: 0.95,
    voiceRate: 0.9,
    voiceGender: "male",
    interests: ["Railway engineering", "Folk music", "Gardening"],
    goals: ["Ensure safe and punctual train dispatch across the city"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_subway_central",
    preferredHangouts: ["loc_sarah_cafe", "loc_oakwood_diner"],
    currentMood: "cheerful",
    vocabularyObjectives: ["fare", "transfer", "interchange", "platform", "single-ride", "tap-in"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 9,
        locationId: "loc_subway_central",
        roomName: "Automated Metro Fare Kiosks",
        activityDescription: "Guiding passengers through touch-screen card reloads",
        arabicActivity: "إرشاد الركاب حول شحن بطاقات المترو",
        dialogueTopic: "Transit Fares & Route Navigation",
      },
    ],
  },
  {
    id: "npc_carl_rental_agent",
    name: "Carl Jenkins",
    age: 34,
    gender: "male",
    occupation: "Skyway Fleet & Car Rental Manager",
    districtId: "transportation",
    locationId: "loc_airport_car_rental",
    locationName: "Skyway Auto & Car Rental",
    avatarEmoji: "🚗",
    avatarColor: "#0891b2",
    personality: "Detail-oriented, friendly, thorough with insurance coverage and navigation devices.",
    speakingStyle: "Clear American Midwestern, structured explanation of contract terms.",
    accent: "American (Midwest)",
    level: "A2",
    relationshipScore: 10,
    relationshipTier: "Stranger",
    memory: [],
    currentScheduleActivity: "Verifying driver licenses and reviewing fuel policies",
    greetingText: "Welcome to Skyway Rentals! Are you looking for a compact city sedan or an all-wheel-drive SUV?",
    defaultTopics: ["Rental Agreements", "Insurance Coverage (Collision Waiver)", "Fuel Policies", "GPS Navigation Add-ons"],
    voicePitch: 0.95,
    voiceRate: 0.95,
    voiceGender: "male",
    interests: ["Automotive mechanics", "Road trips", "Camping"],
    goals: ["Provide safe and reliable vehicles to city visitors"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_airport_car_rental",
    preferredHangouts: ["loc_oakwood_diner", "loc_skyline_cinema"],
    currentMood: "helpful",
    vocabularyObjectives: ["mileage", "deposit", "insurance", "waiver", "fuel policy", "sedan"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 13,
        locationId: "loc_airport_car_rental",
        roomName: "Rental Booking Desk",
        activityDescription: "Explaining insurance terms and handing over vehicle keys",
        arabicActivity: "شرح بنود التأمين وتسليم مفاتيح السيارة",
        dialogueTopic: "Car Rental Contracts & Fuel Policies",
      },
    ],
  },
  {
    id: "npc_barista_liam",
    name: "Liam Bennett",
    age: 22,
    gender: "male",
    occupation: "Commuter Cafe Barista",
    districtId: "transportation",
    locationId: "loc_transit_cafe",
    locationName: "Express Rail Cafe & Bakery",
    avatarEmoji: "☕",
    avatarColor: "#ea580c",
    personality: "Fast-paced, energetic, cheerful, loves morning banter.",
    speakingStyle: "Casual, energetic, fast customer exchanges.",
    accent: "Canadian",
    level: "A1",
    relationshipScore: 10,
    relationshipTier: "Stranger",
    memory: [],
    currentScheduleActivity: "Brewing double-shot espressos for rushing commuters",
    greetingText: "Morning! Large iced latte or hot Americano to catch your train?",
    defaultTopics: ["Quick Coffee Orders", "Pastry Selection", "Next Train Timing"],
    voicePitch: 1.05,
    voiceRate: 1.05,
    voiceGender: "male",
    interests: ["Skateboarding", "Coffee latte art", "Electronic music"],
    goals: ["Open his own artisan coffee cart one day"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_transit_cafe",
    preferredHangouts: ["loc_retro_arcade", "loc_sunset_beach"],
    currentMood: "cheerful",
    vocabularyObjectives: ["takeaway", "skim milk", "extra hot", "receipt", "pastry"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 7,
        locationId: "loc_transit_cafe",
        roomName: "Commuter Coffee Counter",
        activityDescription: "Serving fast morning espressos",
        arabicActivity: "تقديم القهوة الصباحية السريعة",
        dialogueTopic: "Fast Cafe Orders & Payment",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 2. DOWNTOWN CITY CENTER
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_sarah",
    name: "Sarah Miller",
    age: 26,
    gender: "female",
    occupation: "Head Barista & Cafe Owner",
    districtId: "downtown",
    locationId: "loc_sarah_cafe",
    locationName: "Sarah's Artisan Coffee",
    avatarEmoji: "☕",
    avatarColor: "#f59e0b",
    personality: "Warm, bubbly, enthusiastic about coffee and baking, patient with new language learners.",
    speakingStyle: "Friendly, casual conversational, uses upbeat everyday idioms.",
    accent: "American (West Coast)",
    level: "A1",
    relationshipScore: 30,
    relationshipTier: "Friend",
    memory: ["Loves recommending her house specialty vanilla oat latte", "Noticed you are improving your pronunciation"],
    currentScheduleActivity: "Frothing velvety oat milk for morning customers",
    greetingText: "Hey there! Welcome to Sarah's! What can I get brewing for you today?",
    defaultTopics: ["Specialty Coffee Drinks", "Pastries & Breakfast", "English Practice", "Downtown Recommendations"],
    voicePitch: 1.1,
    voiceRate: 1.0,
    voiceGender: "female",
    interests: ["Specialty coffee roasting", "Baking cinnamon rolls", "Indie folk music", "Language exchanges"],
    dislikes: ["Burnt espresso", "Rude attitudes"],
    goals: ["Expand her cafe with an outdoor English conversation patio"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_sarah_cafe",
    preferredHangouts: ["loc_grand_bookstore", "loc_sunset_beach"],
    currentMood: "cheerful",
    vocabularyObjectives: ["latte", "oat milk", "pastry", "blend", "flavor profile", "decaf"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 7,
        locationId: "loc_sarah_cafe",
        roomName: "Main Espresso Bar & Ordering Counter",
        activityDescription: "Brewing fresh single-origin filter roasts",
        arabicActivity: "تحضير قهوة الصباح المختصة",
        dialogueTopic: "Morning Coffee Orders & Customizations",
      },
      {
        timeOfDay: "afternoon",
        hour: 13,
        locationId: "loc_sarah_cafe",
        roomName: "Sunlit Street Patio",
        activityDescription: "Chatting with regulars on the outdoor sun terrace",
        arabicActivity: "التحدث مع الزبائن في الجلسات الخارجية",
        dialogueTopic: "Daily Life in Downtown & Cafe Culture",
      },
      {
        timeOfDay: "evening",
        hour: 18,
        locationId: "loc_grand_bookstore",
        roomName: "Main Literary Hall",
        activityDescription: "Browsing new literature releases at Daniel's bookstore",
        arabicActivity: "تصفح الكتب الجديدة في مكتبة دانيال",
        dialogueTopic: "Book Recommendations & Author Favorites",
      },
    ],
  },
  {
    id: "npc_banker_clara",
    name: "Clara Vance",
    age: 41,
    gender: "female",
    occupation: "Senior Personal Banking Specialist",
    districtId: "downtown",
    locationId: "loc_royal_bank",
    locationName: "Royal Crown Metropolitan Bank",
    avatarEmoji: "💼",
    avatarColor: "#d97706",
    personality: "Polite, methodical, trustworthy, explains complex financial terms simply.",
    speakingStyle: "Professional, articulate British English, clear pronunciation of numbers and rates.",
    accent: "British (Standard RP)",
    level: "A2",
    relationshipScore: 15,
    relationshipTier: "Acquaintance",
    memory: ["Assisted with opening a local debit checking account"],
    currentScheduleActivity: "Reviewing customer account statements and foreign exchange queries",
    greetingText: "Good afternoon. Welcome to Royal Crown Bank. How may I assist you with your banking needs today?",
    defaultTopics: ["Opening a Checking Account", "Foreign Wire Transfers", "Debit & Credit Cards", "Currency Exchange Rates"],
    voicePitch: 1.0,
    voiceRate: 0.95,
    voiceGender: "female",
    interests: ["Macroeconomics", "Classical piano", "Equestrian sports"],
    goals: ["Help international residents manage their finances smoothly"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_royal_bank",
    preferredHangouts: ["loc_metro_museum", "loc_oxford_hall"],
    currentMood: "helpful",
    vocabularyObjectives: ["checking account", "savings", "interest rate", "wire transfer", "PIN number", "statement"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 10,
        locationId: "loc_royal_bank",
        roomName: "Teller Desks & Account Services",
        activityDescription: "Opening checking accounts for new city arrivals",
        arabicActivity: "فتح حسابات جارية للقادمين الجدد",
        dialogueTopic: "Bank Account Opening & Documentation",
      },
    ],
  },
  {
    id: "npc_bookseller_daniel",
    name: "Daniel Hawthorne",
    age: 58,
    gender: "male",
    occupation: "Literary Curator & Bookseller",
    districtId: "downtown",
    locationId: "loc_grand_bookstore",
    locationName: "Grand Central Heritage Bookstore",
    avatarEmoji: "📚",
    avatarColor: "#b45309",
    personality: "Wise, gentle, passionate about English literature, poetry, and idioms.",
    speakingStyle: "Eloquent, measured, uses rich vocabulary with helpful paraphrasing.",
    accent: "British (Oxford Academic)",
    level: "A2",
    relationshipScore: 25,
    relationshipTier: "Friend",
    memory: ["Recommended an easy graded reader book for A2 practice", "Sarah from the cafe is his regular book club friend"],
    currentScheduleActivity: "Shelving classic novels and graded readers",
    greetingText: "Ah, welcome to my sanctuary of words! Are you searching for a gripping novel, or perhaps a dictionary of English idioms?",
    defaultTopics: ["Book Recommendations by CEFR Level", "English Idioms & Expressions", "Author Biographies", "Book Club Meetings"],
    voicePitch: 0.9,
    voiceRate: 0.85,
    voiceGender: "male",
    interests: ["19th-century literature", "Bookbinding", "Linguistics", "Chess"],
    goals: ["Foster a love of reading in language learners"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_grand_bookstore",
    preferredHangouts: ["loc_sarah_cafe", "loc_metro_museum"],
    currentMood: "cheerful",
    vocabularyObjectives: ["novel", "genre", "author", "metaphor", "bestseller", "graded reader"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 14,
        locationId: "loc_grand_bookstore",
        roomName: "Main Literary Hall",
        activityDescription: "Guiding readers to the ESL and graded classics section",
        arabicActivity: "إرشاد القراء إلى قسم تعليم اللغة والروايات المبسطة",
        dialogueTopic: "Selecting English Books & Graded Readers",
      },
    ],
  },
  {
    id: "npc_postal_clerk_rachel",
    name: "Rachel Simmons",
    age: 32,
    gender: "female",
    occupation: "Postal Operations Officer",
    districtId: "downtown",
    locationId: "loc_downtown_post_office",
    locationName: "Central Post & Courier Depot",
    avatarEmoji: "📦",
    avatarColor: "#e11d48",
    personality: "Efficient, clear, upbeat, skilled at explaining international shipping options.",
    speakingStyle: "Clear American Standard, precise instructions on customs forms.",
    accent: "American (General)",
    level: "A2",
    relationshipScore: 10,
    relationshipTier: "Stranger",
    memory: [],
    currentScheduleActivity: "Weighing parcels and stamping airmail tracking slips",
    greetingText: "Hello! Standard ground shipping or express airmail for this parcel?",
    defaultTopics: ["Sending International Mail", "Tracking Numbers", "Packaging & Fragile Items", "Postage Stamps"],
    voicePitch: 1.0,
    voiceRate: 1.0,
    voiceGender: "female",
    interests: ["Philately (stamp collecting)", "Marathons", "Calligraphy"],
    goals: ["Ensure every letter and parcel arrives securely across the globe"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_downtown_post_office",
    preferredHangouts: ["loc_sarah_cafe", "loc_bloom_nursery"],
    currentMood: "helpful",
    vocabularyObjectives: ["postage", "airmail", "fragile", "tracking number", "customs label", "envelope"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 11,
        locationId: "loc_downtown_post_office",
        roomName: "Parcel Weighing & Stamp Counter",
        activityDescription: "Processing international airmail packages",
        arabicActivity: "معالجة الطرود البريدية الجوية الدولية",
        dialogueTopic: "Postal Rates & Shipping Options",
      },
    ],
  },
  {
    id: "npc_chef_marco",
    name: "Marco Bellini",
    age: 46,
    gender: "male",
    occupation: "Executive Chef & Trattoria Owner",
    districtId: "downtown",
    locationId: "loc_bella_trattoria",
    locationName: "Bella Italia Ristorante",
    avatarEmoji: "👨‍🍳",
    avatarColor: "#059669",
    personality: "Passionate, jovial, loves describing dishes and ingredients in sensory detail.",
    speakingStyle: "Expressive, warm, loves food vocabulary and culinary descriptions.",
    accent: "Italian-accented English (clear & melodious)",
    level: "A2",
    relationshipScore: 15,
    relationshipTier: "Acquaintance",
    memory: ["Explained the difference between fresh basil pesto and marinara"],
    currentScheduleActivity: "Tasting the evening risotto and explaining specials to guests",
    greetingText: "Buonasera! Welcome to Bella Italia! Have you saved room for handmade truffle tagliatelle?",
    defaultTopics: ["Italian Specialties", "Dietary Needs & Allergies", "Wine & Dish Pairings", "Ordering in English"],
    voicePitch: 0.95,
    voiceRate: 0.95,
    voiceGender: "male",
    interests: ["Authentic Mediterranean cuisine", "Herb gardening", "Opera"],
    goals: ["Serve the most delicious and welcoming food in English City"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_bella_trattoria",
    preferredHangouts: ["loc_superfresh_market", "loc_sarah_cafe"],
    currentMood: "cheerful",
    vocabularyObjectives: ["appetizer", "main course", "vegetarian", "gluten-free", "homemade", "bill"],
    schedule: [
      {
        timeOfDay: "evening",
        hour: 19,
        locationId: "loc_bella_trattoria",
        roomName: "Main Dining Hall",
        activityDescription: "Greeting dinner guests and taking custom orders",
        arabicActivity: "استقبال رواد العشاء وتسجيل الطلبات الخاصة",
        dialogueTopic: "Restaurant Ordering & Dietary Preferences",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 3. RESIDENTIAL DISTRICT
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_neighbor_lucas",
    name: "Lucas Vance",
    age: 28,
    gender: "male",
    occupation: "Graphic Designer & Next-Door Neighbor (Apt 4A)",
    districtId: "residential",
    locationId: "loc_apartment",
    locationName: "Maplewood Residential Lofts",
    avatarEmoji: "🎨",
    avatarColor: "#10b981",
    personality: "Laid-back, friendly, artistic, always willing to lend a tool or recommend local spots.",
    speakingStyle: "Casual conversational American, helpful with everyday neighbor phrases.",
    accent: "American (Pacific Northwest)",
    level: "A1",
    relationshipScore: 35,
    relationshipTier: "Friend",
    memory: ["Welcomed you to Maplewood Lofts", "Shared his Wi-Fi password when you first moved in"],
    currentScheduleActivity: "Watering balcony herbs and checking the building notice board",
    greetingText: "Hey Alex! Good to see you in the hallway! How's your English study going today?",
    defaultTopics: ["Apartment Living & Utilities", "Borrowing Household Tools", "Neighborhood Coffee & Groceries", "Weekend Plans"],
    voicePitch: 1.0,
    voiceRate: 1.0,
    voiceGender: "male",
    interests: ["Digital illustration", "Cycling", "Indie games", "Coffee"],
    goals: ["Finish his freelance graphic novel design"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_synergy_coworking",
    preferredHangouts: ["loc_sarah_cafe", "loc_skyline_cinema"],
    currentMood: "cheerful",
    vocabularyObjectives: ["neighbor", "borrow", "utility bill", "package", "maintenance", "balcony"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 8,
        locationId: "loc_apartment",
        roomName: "Alex's Studio Apartment",
        activityDescription: "Checking the apartment mailboxes and greeting neighbors",
        arabicActivity: "تفقد صناديق البريد والترحيب بالجيران",
        dialogueTopic: "Morning Greetings & Neighborly Small Talk",
      },
      {
        timeOfDay: "afternoon",
        hour: 14,
        locationId: "loc_corner_bakery",
        roomName: "Fresh Bread & Pastry Counter",
        activityDescription: "Grabbing a sourdough loaf at Elena's bakery",
        arabicActivity: "شراء خبز طازج من مخبز إيلينا",
        dialogueTopic: "Daily Bakery Errands & Recommendations",
      },
    ],
  },
  {
    id: "npc_baker_elena",
    name: "Elena Rostova",
    age: 45,
    gender: "female",
    occupation: "Master Baker & Patisserie Artisan",
    districtId: "residential",
    locationId: "loc_corner_bakery",
    locationName: "Honeycomb Artisan Bakery",
    avatarEmoji: "🥖",
    avatarColor: "#d97706",
    personality: "Warm, maternal, passionate about crusty bread, sourdough starters, and tea.",
    speakingStyle: "Gentle, clear English with a hint of Eastern European warmth.",
    accent: "Eastern European / International",
    level: "A1",
    relationshipScore: 25,
    relationshipTier: "Friend",
    memory: ["Gave you an extra warm cinnamon roll on your first visit"],
    currentScheduleActivity: "Pulling golden baguettes out of the deck oven",
    greetingText: "Good morning, dear! Everything is fresh from the oven. Would you like a warm baguette or a blueberry scone?",
    defaultTopics: ["Bread Varieties (Sourdough, Rye, Whole Grain)", "Pastries & Cakes", "Baking Ingredients", "Daily Routine"],
    voicePitch: 1.05,
    voiceRate: 0.9,
    voiceGender: "female",
    interests: ["Sourdough fermentation", "Gardening", "Traditional folklore"],
    goals: ["Bake nourishing bread that brings the neighborhood together"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_corner_bakery",
    preferredHangouts: ["loc_bloom_nursery", "loc_community_center"],
    currentMood: "cheerful",
    vocabularyObjectives: ["loaf", "sourdough", "whole wheat", "slice", "dozen", "freshly baked"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 6,
        locationId: "loc_corner_bakery",
        roomName: "Fresh Bread & Pastry Counter",
        activityDescription: "Baking morning loaves and greeting neighbors",
        arabicActivity: "خبز المعجنات الصباحية واستقبال الجيران",
        dialogueTopic: "Ordering Bakery Items & Asking for Quantities",
      },
    ],
  },
  {
    id: "npc_neighbor_mrs_patel",
    name: "Mrs. Ananya Patel",
    age: 62,
    gender: "female",
    occupation: "Retired School Librarian & Neighborhood Watch Volunteer",
    districtId: "residential",
    locationId: "loc_neighborhood_laundromat",
    locationName: "CleanWave 24/7 Laundromat",
    avatarEmoji: "👵",
    avatarColor: "#06b6d4",
    personality: "Kind, observant, loves chatting about weather, gardening, and community safety.",
    speakingStyle: "Clear, deliberate, polite Indian English, encouraging and respectful.",
    accent: "Indian English (Standard)",
    level: "A1",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: ["Showed you how the detergent dispenser works in the laundromat"],
    currentScheduleActivity: "Folding clean linens and chatting with neighborhood residents",
    greetingText: "Namaste and hello! How are you finding our peaceful neighborhood?",
    defaultTopics: ["Laundromat Instructions", "Weather & Gardening", "Community Clean-up Days", "Local Recipes"],
    voicePitch: 1.0,
    voiceRate: 0.88,
    voiceGender: "female",
    interests: ["Herbal gardening", "Knitting", "Community volunteering"],
    goals: ["Keep the neighborhood friendly, safe, and connected"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_community_center",
    preferredHangouts: ["loc_bloom_nursery", "loc_grand_bookstore"],
    currentMood: "cheerful",
    vocabularyObjectives: ["detergent", "cycle", "delicate", "dryer", "community", "safety"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 15,
        locationId: "loc_neighborhood_laundromat",
        roomName: "Main Washer & Dryer Floor",
        activityDescription: "Doing afternoon laundry and helping neighbors with machine settings",
        arabicActivity: "غسيل الملابس ومساعدة الجيران في إعدادات الغسالات",
        dialogueTopic: "Using Household Appliances & Community Talk",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 4. SHOPPING & PROMENADE
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_michael",
    name: "Michael Sterling",
    age: 35,
    gender: "male",
    occupation: "Hypermarket Customer Experience Manager",
    districtId: "shopping",
    locationId: "loc_superfresh_market",
    locationName: "SuperFresh Hypermarket & Groceries",
    avatarEmoji: "🛒",
    avatarColor: "#10b981",
    personality: "Organized, energetic, helpful, skilled at resolving product inquiries and returns.",
    speakingStyle: "Direct, friendly retail English, patient with aisle directions and price inquiries.",
    accent: "American (General)",
    level: "A2",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: ["Assisted you with finding organic olive oil and comparing dairy brands"],
    currentScheduleActivity: "Inspecting organic produce displays in Aisle 4",
    greetingText: "Welcome to SuperFresh! Looking for any specific ingredients or today's weekly specials?",
    defaultTopics: ["Finding Grocery Aisles", "Comparing Prices & Brands", "Store Return Policy", "Organic vs Conventional"],
    voicePitch: 0.95,
    voiceRate: 1.0,
    voiceGender: "male",
    interests: ["Healthy cooking", "Supply chain logistics", "Marathons"],
    goals: ["Make SuperFresh the most learner-friendly supermarket in town"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_superfresh_market",
    preferredHangouts: ["loc_volt_electronics", "loc_sarah_cafe"],
    currentMood: "helpful",
    vocabularyObjectives: ["aisle", "organic", "expiration date", "discount", "receipt", "refund"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 10,
        locationId: "loc_superfresh_market",
        roomName: "Organic Produce & Grocery Aisles",
        activityDescription: "Managing grocery stock and helping shoppers find ingredients",
        arabicActivity: "إدارة البضائع ومساعدة المتسوقين في إيجاد المواد",
        dialogueTopic: "Asking for Ingredients & Checking Prices",
      },
    ],
  },
  {
    id: "npc_stylist_olivia",
    name: "Olivia Chen",
    age: 27,
    gender: "female",
    occupation: "Fashion Consultant & Boutique Stylist",
    districtId: "shopping",
    locationId: "loc_luxe_boutique",
    locationName: "Luxe Thread Apparel & Boutique",
    avatarEmoji: "👗",
    avatarColor: "#ec4899",
    personality: "Chic, observant, enthusiastic, skilled at matching outfits and advising on fit.",
    speakingStyle: "Trendy, polite, descriptive with colors, fabrics, and clothing sizes.",
    accent: "British / London Modern",
    level: "A2",
    relationshipScore: 15,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Arranging autumn jacket displays and assisting in fitting suites",
    greetingText: "Hello darling! Looking for something smart-casual or a formal blazer for work?",
    defaultTopics: ["Trying On Clothes (Fitting Rooms)", "Size Exchanges (Small/Medium/Large)", "Fabrics & Care (Cotton, Wool, Silk)", "Refunds & Exchange Policy"],
    voicePitch: 1.05,
    voiceRate: 1.0,
    voiceGender: "female",
    interests: ["Fashion design", "Vintage clothing", "Modern photography"],
    goals: ["Help every customer feel confident in their clothing choices"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_luxe_boutique",
    preferredHangouts: ["loc_sarah_cafe", "loc_skyline_cinema"],
    currentMood: "cheerful",
    vocabularyObjectives: ["fitting room", "tight", "loose", "size up", "wool", "exchange"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 14,
        locationId: "loc_luxe_boutique",
        roomName: "Apparel Showroom & Fitting Suites",
        activityDescription: "Helping shoppers try on coats and check sizes",
        arabicActivity: "مساعدة المتسوقين في قياس المعاطف واختيار المقاسات",
        dialogueTopic: "Shopping for Clothes, Sizes & Fitting Rooms",
      },
    ],
  },
  {
    id: "npc_tech_advisor_kevin",
    name: "Kevin Park",
    age: 25,
    gender: "male",
    occupation: "Smart Electronics Sales Specialist",
    districtId: "shopping",
    locationId: "loc_volt_electronics",
    locationName: "VoltTech Smart Electronics",
    avatarEmoji: "💻",
    avatarColor: "#3b82f6",
    personality: "Tech-savvy, enthusiastic, clear at explaining specs, battery life, and warranties.",
    speakingStyle: "Modern conversational English, good at comparing gadgets without overly dense jargon.",
    accent: "American (West Coast)",
    level: "B1",
    relationshipScore: 15,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Demonstrating noise-canceling headphones at the demo bench",
    greetingText: "Hey there! Looking to upgrade your laptop, phone, or find some great headphones for studying?",
    defaultTopics: ["Laptop & Tablet Specs", "Battery Life & Storage (GB/TB)", "Extended Warranties & Protection", "Trade-In Programs"],
    voicePitch: 1.0,
    voiceRate: 1.05,
    voiceGender: "male",
    interests: ["PC building", "Artificial intelligence", "Esports"],
    goals: ["Build his own tech review channel"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_volt_electronics",
    preferredHangouts: ["loc_retro_arcade", "loc_synergy_coworking"],
    currentMood: "cheerful",
    vocabularyObjectives: ["specifications", "battery life", "warranty", "processor", "storage", "trade-in"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 16,
        locationId: "loc_volt_electronics",
        roomName: "Interactive Device Test Bench",
        activityDescription: "Demoing gadgets and explaining warranty plans",
        arabicActivity: "تجربة الأجهزة الذكية وشرح خطط الضمان",
        dialogueTopic: "Comparing Tech Specs & Warranties",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 5. INNOVATION & TECH PLAZA
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_maya",
    name: "Maya Chen",
    age: 33,
    gender: "female",
    occupation: "VP of Software Engineering & AI Architect",
    districtId: "business",
    locationId: "loc_nexus_tech",
    locationName: "Nexus Tech Innovations Tower",
    avatarEmoji: "👩‍💼",
    avatarColor: "#6366f1",
    personality: "Visionary, articulate, ambitious, structured thinker, high standards for technical communication.",
    speakingStyle: "Professional executive English, crisp tech terminology, STAR framework in interviews.",
    accent: "American (Silicon Valley / Standard)",
    level: "B1",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: ["Conducted your technical interview for the Junior Developer role", "Praised your structured explanation of problem-solving"],
    currentScheduleActivity: "Leading the quarterly product roadmap sync in Boardroom A",
    greetingText: "Good morning. In our agile engineering culture, clear communication is as crucial as clean code. What's on your agenda?",
    defaultTopics: ["Software Architecture & APIs", "Agile Sprints & Standups", "Job Interviewing (STAR Method)", "Negotiating Deadlines"],
    voicePitch: 1.0,
    voiceRate: 1.0,
    voiceGender: "female",
    interests: ["Neural networks", "Cloud architecture", "Trail running", "Sci-fi literature"],
    dislikes: ["Vague updates", "Missed sprint deadlines"],
    goals: ["Lead Nexus Tech to an international AI platform launch"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_nexus_tech",
    preferredHangouts: ["loc_synergy_coworking", "loc_sarah_cafe"],
    currentMood: "busy",
    vocabularyObjectives: ["scalable", "infrastructure", "pull request", "stakeholder", "deadline", "deliverable"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 9,
        locationId: "loc_nexus_tech",
        roomName: "Boardroom A & Presentation Suite",
        activityDescription: "Reviewing code submissions and sprint deliverables",
        arabicActivity: "مراجعة كود المطورين ومخرجات مرحلة العمل",
        dialogueTopic: "Agile Standups & Sprint Deliverables",
      },
      {
        timeOfDay: "afternoon",
        hour: 15,
        locationId: "loc_nexus_tech",
        roomName: "Boardroom A & Presentation Suite",
        activityDescription: "Conducting candidate interviews for engineering positions",
        arabicActivity: "إجراء مقابلات التوظيف للمرشحين الجدد",
        dialogueTopic: "Technical Job Interviews & STAR Answers",
      },
    ],
  },
  {
    id: "npc_founder_zack",
    name: "Zack Robinson",
    age: 30,
    gender: "male",
    occupation: "Tech Startup Founder & Product Lead",
    districtId: "business",
    locationId: "loc_synergy_coworking",
    locationName: "Synergy Open Coworking Commons",
    avatarEmoji: "🚀",
    avatarColor: "#8b5cf6",
    personality: "High-energy, optimistic, enthusiastic about startups, investor pitches, and MVP validation.",
    speakingStyle: "Fast-paced, modern business English, uses venture capital and growth terms.",
    accent: "American (West Coast)",
    level: "B2",
    relationshipScore: 15,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Polishing his Seed Series pitch deck for angel investors",
    greetingText: "Hey! Are you working on a new startup project? Let's grab some cold brew and talk product-market fit!",
    defaultTopics: ["Startup Pitch Decks", "Venture Capital & Seed Rounds", "Product-Market Fit", "Networking in English"],
    voicePitch: 1.05,
    voiceRate: 1.05,
    voiceGender: "male",
    interests: ["Fintech", "Angel investing", "Podcasting"],
    goals: ["Raise Series A funding for his collaborative SaaS app"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_synergy_coworking",
    preferredHangouts: ["loc_sarah_cafe", "loc_sunset_beach"],
    currentMood: "cheerful",
    vocabularyObjectives: ["venture capital", "traction", "burn rate", "MVP", "pitch deck", "valuation"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 14,
        locationId: "loc_synergy_coworking",
        roomName: "Networking & Hot-Desk Lounge",
        activityDescription: "Rehearsing investor pitch presentations",
        arabicActivity: "التدرب على عروض المستثمرين التقديمية",
        dialogueTopic: "Business Pitches & Startup Terminology",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 6. OXFORD UNIVERSITY
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_prof_holloway",
    name: "Professor Alistair Holloway",
    age: 54,
    gender: "male",
    occupation: "Chair of Linguistics & English Literature",
    districtId: "university",
    locationId: "loc_oxford_hall",
    locationName: "Oxford Humanities Lecture Amphitheater",
    avatarEmoji: "🎓",
    avatarColor: "#f59e0b",
    personality: "Scholarly, encouraging, intellectually rigorous, appreciates nuanced argumentation.",
    speakingStyle: "Aristocratic British RP, formal academic diction, rhetorical balance.",
    accent: "British Oxford Academic",
    level: "B2",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: ["Assessed your academic essay thesis on language acquisition"],
    currentScheduleActivity: "Preparing notes for the weekly comparative rhetoric symposium",
    greetingText: "Greetings. In this hall, words are not merely communicated; they are analyzed, crafted, and debated. Welcome.",
    defaultTopics: ["Academic Essays & Thesis Formulation", "Debating Complex Arguments", "Etymology & Linguistic Evolution", "Scholarly Research Methods"],
    voicePitch: 0.88,
    voiceRate: 0.88,
    voiceGender: "male",
    interests: ["Historical linguistics", "Classical rhetoric", "Antique fountain pens"],
    dislikes: ["Logical fallacies", "Unsupported claims"],
    goals: ["Guide students toward eloquent, high-level mastery of English"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_oxford_hall",
    preferredHangouts: ["loc_bodleian_library", "loc_grand_bookstore"],
    currentMood: "helpful",
    vocabularyObjectives: ["hypothesis", "empirical", "rhetoric", "methodology", "counter-argument", "thesis"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 10,
        locationId: "loc_oxford_hall",
        roomName: "Great Humanities Lecture Hall",
        activityDescription: "Delivering a lecture on formal rhetoric and debate",
        arabicActivity: "إلقاء محاضرة حول البلاغة والمناظرة الأكاديمية",
        dialogueTopic: "Formal Academic English & Thesis Defense",
      },
    ],
  },
  {
    id: "npc_librarian_arthur",
    name: "Arthur Pendelton",
    age: 60,
    gender: "male",
    occupation: "Bodleian Archival Research Librarian",
    districtId: "university",
    locationId: "loc_bodleian_library",
    locationName: "Bodleian Central Research Library",
    avatarEmoji: "📖",
    avatarColor: "#78350f",
    personality: "Quiet, whisper-toned, immensely knowledgeable about journal databases and citations.",
    speakingStyle: "Quiet, precise, formal academic vocabulary, stresses library etiquette.",
    accent: "British (Standard)",
    level: "B2",
    relationshipScore: 15,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Assisting researchers with peer-reviewed journal citations",
    greetingText: "Shh... Welcome to the Bodleian. How may I assist your scholarly research today?",
    defaultTopics: ["Academic Citations (APA, Harvard, MLA)", "Searching Peer-Reviewed Journals", "Library Research Databases", "Silent Study Protocols"],
    voicePitch: 0.9,
    voiceRate: 0.85,
    voiceGender: "male",
    interests: ["Manuscript preservation", "Genealogy", "Renaissance history"],
    goals: ["Preserve academic knowledge for future scholars"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_bodleian_library",
    preferredHangouts: ["loc_oxford_hall", "loc_grand_bookstore"],
    currentMood: "helpful",
    vocabularyObjectives: ["citation", "peer-reviewed", "archive", "manuscript", "bibliography", "abstract"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 13,
        locationId: "loc_bodleian_library",
        roomName: "Archival Reading Room",
        activityDescription: "Helping students locate academic journal archives",
        arabicActivity: "مساعدة الطلاب في البحث في أرشيف المجلات الأكاديمية",
        dialogueTopic: "Academic Citations & Research Papers",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 7. ST. JUDE MEDICAL CENTER
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_dr_hayes",
    name: "Dr. Jonathan Hayes",
    age: 48,
    gender: "male",
    occupation: "Senior Attending Physician & Clinical Director",
    districtId: "medical",
    locationId: "loc_stjude_hospital",
    locationName: "St. Jude General Hospital",
    avatarEmoji: "🩺",
    avatarColor: "#ef4444",
    personality: "Compassionate, calm, reassuring, highly attentive to symptom descriptions and patient concerns.",
    speakingStyle: "Gentle, clear, empathetic medical English, explains diagnoses in accessible everyday terms.",
    accent: "Neutral British/International",
    level: "A2",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: ["Checked symptoms for seasonal allergies and explained dosage instructions"],
    currentScheduleActivity: "Conducting clinical consultations in Suite 204",
    greetingText: "Hello there. Please have a seat. Tell me, how have you been feeling, and what brings you into the clinic today?",
    defaultTopics: ["Describing Symptoms & Duration", "Pain Levels & Discomfort", "Prescription Instructions", "Medical History & Follow-ups"],
    voicePitch: 0.92,
    voiceRate: 0.9,
    voiceGender: "male",
    interests: ["Preventative medicine", "Medical ethics", "Classical violin"],
    dislikes: ["Patients ignoring dosage safety warnings"],
    goals: ["Provide safe, empathetic clinical care and clear patient communication"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_stjude_hospital",
    preferredHangouts: ["loc_sarah_cafe", "loc_greenfield_school"],
    currentMood: "helpful",
    vocabularyObjectives: ["symptoms", "prescription", "dosage", "side effects", "allergy", "drowsiness"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 9,
        locationId: "loc_stjude_hospital",
        roomName: "Dr. Hayes Consultation Suite 204",
        activityDescription: "Examining patients and listening to symptom histories",
        arabicActivity: "فحص المرضى والاستماع لتاريخ الأعراض",
        dialogueTopic: "Describing Symptoms & Medical History",
      },
    ],
  },
  {
    id: "npc_pharmacist_maya",
    name: "Maya Lin, PharmD",
    age: 36,
    gender: "female",
    occupation: "Clinical Dispensing Pharmacist",
    districtId: "medical",
    locationId: "loc_stjude_hospital",
    locationName: "St. Jude General Hospital",
    avatarEmoji: "💊",
    avatarColor: "#059669",
    personality: "Precise, reassuring, thorough with medication warnings and food interactions.",
    speakingStyle: "Clear, patient, structured explanation of frequency and dosage times.",
    accent: "American (Standard)",
    level: "A2",
    relationshipScore: 15,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Dispensing antibiotics and explaining mealtime warnings",
    greetingText: "Good day! I have your prescription ready. Let me explain how and when you should take these tablets.",
    defaultTopics: ["Prescription Pick-up", "Dosage Instructions (Take with Food, Twice Daily)", "Side Effects & Precautions", "Over-the-Counter Remedies"],
    voicePitch: 1.0,
    voiceRate: 0.95,
    voiceGender: "female",
    interests: ["Pharmacology", "Herbal remedies", "Cycling"],
    goals: ["Ensure every patient understands safe medication usage"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_stjude_hospital",
    preferredHangouts: ["loc_superfresh_market", "loc_sarah_cafe"],
    currentMood: "helpful",
    vocabularyObjectives: ["tablet", "capsule", "dosage", "refill", "take with food", "drowsy"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 14,
        locationId: "loc_stjude_hospital",
        roomName: "St. Jude Dispensary & Pharmacy",
        activityDescription: "Explaining medication directions at the pharmacy pickup window",
        arabicActivity: "شرح تعليمات تناول الدواء في شباك الصيدلية",
        dialogueTopic: "Pharmacy Pickups & Medication Instructions",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 8. STARLIGHT ENTERTAINMENT DISTRICT
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_leo",
    name: "Leo Martinez",
    age: 24,
    gender: "male",
    occupation: "Cinema Operations Lead & Film Enthusiast",
    districtId: "entertainment",
    locationId: "loc_skyline_cinema",
    locationName: "Skyline Multiplex & IMAX",
    avatarEmoji: "🍿",
    avatarColor: "#d946ef",
    personality: "Enthusiastic, pop-culture savvy, loves discussing plot twists, genres, and movie trivia.",
    speakingStyle: "Casual, expressive American English with lively idioms and conversational slang.",
    accent: "American (California)",
    level: "A2",
    relationshipScore: 25,
    relationshipTier: "Friend",
    memory: ["Recommended the IMAX screening of the new sci-fi thriller", "Loves making large sweet-and-salty popcorn combos"],
    currentScheduleActivity: "Managing box office reservations and movie trailers",
    greetingText: "Hey there! Ready for the big screen? Are you in the mood for action, comedy, or a mind-bending thriller?",
    defaultTopics: ["Movie Genres & Plot Discussions", "Showtimes & Ticket Reservations (Matinee vs Evening)", "Favorite Actors & Directors", "Cinema Concessions"],
    voicePitch: 1.05,
    voiceRate: 1.05,
    voiceGender: "male",
    interests: ["Cinematography", "Pop culture podcasts", "Screenwriting", "Gaming"],
    goals: ["Direct his own independent short film"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_skyline_cinema",
    preferredHangouts: ["loc_retro_arcade", "loc_sarah_cafe"],
    currentMood: "cheerful",
    vocabularyObjectives: ["screening", "matinee", "subtitles", "blockbuster", "soundtrack", "popcorn"],
    schedule: [
      {
        timeOfDay: "evening",
        hour: 18,
        locationId: "loc_skyline_cinema",
        roomName: "Cinema Box Office & Popcorn Bar",
        activityDescription: "Handling box office ticket queues and seat reservations",
        arabicActivity: "إدارة طوابير التذاكر وحجز المقاعد",
        dialogueTopic: "Buying Cinema Tickets & Discussing Movies",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 9. GREENFIELD SUBURBS
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_teacher_hannah",
    name: "Hannah Cooper",
    age: 31,
    gender: "female",
    occupation: "Elementary School Educator & Community Coordinator",
    districtId: "suburbs",
    locationId: "loc_greenfield_school",
    locationName: "Greenfield Community Elementary School",
    avatarEmoji: "👩‍🏫",
    avatarColor: "#16a34a",
    personality: "Gentle, supportive, highly encouraging with English learners, loves community events.",
    speakingStyle: "Clear, warm, well-enunciated English, excellent pacing.",
    accent: "Neutral American",
    level: "A1",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Organizing the suburban community literacy fair",
    greetingText: "Hello and welcome to Greenfield! Are you here for the school calendar updates or our community reading circle?",
    defaultTopics: ["School Activities & Calendar", "Suburban Family Life", "Community Workshops", "Everyday English Practice"],
    voicePitch: 1.05,
    voiceRate: 0.92,
    voiceGender: "female",
    interests: ["Early education", "Children's literature", "Gardening"],
    goals: ["Build strong neighborhood literacy programs"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_greenfield_school",
    preferredHangouts: ["loc_bloom_nursery", "loc_oakwood_diner"],
    currentMood: "cheerful",
    vocabularyObjectives: ["recess", "field trip", "semester", "volunteer", "parent-teacher", "homework"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 9,
        locationId: "loc_greenfield_school",
        roomName: "Parent-Teacher Reception Office",
        activityDescription: "Answering parent inquiries about school activities",
        arabicActivity: "الرد على استفسارات أولياء الأمور حول الأنشطة",
        dialogueTopic: "School Schedules & Community Events",
      },
    ],
  },
  {
    id: "npc_gardener_george",
    name: "George Miller",
    age: 57,
    gender: "male",
    occupation: "Master Horticulturist & Nursery Owner",
    districtId: "suburbs",
    locationId: "loc_bloom_nursery",
    locationName: "Bloom & Grow Garden Nursery",
    avatarEmoji: "🌱",
    avatarColor: "#65a30d",
    personality: "Down-to-earth, patient, enthusiastic about soil, seasons, and organic vegetables.",
    speakingStyle: "Friendly, rustic American English, uses nature metaphors.",
    accent: "American (Rural/Midwest)",
    level: "A1",
    relationshipScore: 15,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Pruning hydrangeas and mixing potting compost",
    greetingText: "Well howdy! Looking for some hardy perennials or seeds for your balcony garden?",
    defaultTopics: ["Plant Care (Watering & Sunlight)", "Seasonal Weather & Frost", "Growing Herbs at Home", "Suburban Yard Work"],
    voicePitch: 0.9,
    voiceRate: 0.9,
    voiceGender: "male",
    interests: ["Bonsai cultivation", "Organic composting", "Birdwatching"],
    goals: ["Help every neighbor grow their own fresh basil and tomatoes"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_bloom_nursery",
    preferredHangouts: ["loc_oakwood_diner", "loc_corner_bakery"],
    currentMood: "cheerful",
    vocabularyObjectives: ["sunlight", "fertilizer", "pruning", "drainage", "perennial", "seeds"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 13,
        locationId: "loc_bloom_nursery",
        roomName: "Indoor Flora & Seed Station",
        activityDescription: "Advising customers on potting soil and sunlight requirements",
        arabicActivity: "إرشاد الزبائن حول التربة واحتياجات ضوء الشمس",
        dialogueTopic: "Caring for Plants & Weather Conversations",
      },
    ],
  },
  {
    id: "npc_diner_waitress_ruby",
    name: "Ruby Hayes",
    age: 40,
    gender: "female",
    occupation: "Lead Server at Oakwood Diner",
    districtId: "suburbs",
    locationId: "loc_oakwood_diner",
    locationName: "Oakwood Family Diner & Grill",
    avatarEmoji: "🥞",
    avatarColor: "#f97316",
    personality: "Fast-talking, big-hearted, classic diner charm, calls everyone 'hon'.",
    speakingStyle: "Upbeat, casual American English, rapid order-taking phrases.",
    accent: "American (Southern / Friendly)",
    level: "A1",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Pouring bottomless coffee refills and serving pancake stacks",
    greetingText: "Hey there hon! Slide into any booth you like! Coffee to start?",
    defaultTopics: ["Diner Breakfast Orders", "Eggs Your Way (Scrambled, Fried, Poached)", "Side Orders & Refills", "Local Suburban Gossip"],
    voicePitch: 1.1,
    voiceRate: 1.05,
    voiceGender: "female",
    interests: ["Country music", "Baking apple pies", "Vintage diner memorabilia"],
    goals: ["Ensure nobody leaves her diner hungry"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_oakwood_diner",
    preferredHangouts: ["loc_bloom_nursery", "loc_greenfield_school"],
    currentMood: "cheerful",
    vocabularyObjectives: ["scrambled", "over-easy", "toast", "pancakes", "refill", "side order"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 8,
        locationId: "loc_oakwood_diner",
        roomName: "Family Dining Area",
        activityDescription: "Taking breakfast orders and pouring coffee",
        arabicActivity: "تسجيل طلبات الإفطار وصب القهوة",
        dialogueTopic: "Ordering Breakfast at a Diner",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 10. HERITAGE & TOURIST QUARTER
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_elena",
    name: "Elena Rostova",
    age: 32,
    gender: "female",
    occupation: "Head Concierge & Hospitality Manager",
    districtId: "tourist",
    locationId: "loc_grand_hotel",
    locationName: "The Grand Horizon Luxury Hotel",
    avatarEmoji: "🛎️",
    avatarColor: "#f97316",
    personality: "Elegant, multilingual, exceptionally polite, master of five-star hospitality etiquette.",
    speakingStyle: "Refined, gracious, high-register polite British English, exemplary customer service.",
    accent: "Neutral European / International RP",
    level: "A2",
    relationshipScore: 25,
    relationshipTier: "Friend",
    memory: ["Booked your scenic river cruise and recommended the heritage walking tour"],
    currentScheduleActivity: "Arranging VIP limousine transfers and theater tickets at the concierge desk",
    greetingText: "A very warm welcome to The Grand Horizon. Allow me to ensure your stay in English City is nothing short of extraordinary.",
    defaultTopics: ["Hotel Check-in & Room Amenities", "City Excursion & Tour Bookings", "Dining Reservations & Recommendations", "Luggage & Valet Services"],
    voicePitch: 1.0,
    voiceRate: 0.95,
    voiceGender: "female",
    interests: ["World architecture", "Ballet", "Culinary tourism", "Hotel management"],
    dislikes: ["Subpar service", "Tardiness"],
    goals: ["Maintain The Grand Horizon's prestigious 5-star rating"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_grand_hotel",
    preferredHangouts: ["loc_metro_museum", "loc_bella_trattoria"],
    currentMood: "helpful",
    vocabularyObjectives: ["reservation", "amenities", "complimentary", "suite", "concierge", "itinerary"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 14,
        locationId: "loc_grand_hotel",
        roomName: "Front Desk & Concierge Desk",
        activityDescription: "Assisting guests with checking in and booking city excursions",
        arabicActivity: "مساعدة النزلاء في تسجيل الدخول وحجز الجولات السياحية",
        dialogueTopic: "Hotel Check-ins & Concierge Recommendations",
      },
    ],
  },
  {
    id: "npc_curator_beatrice",
    name: "Beatrice Montgomery",
    age: 49,
    gender: "female",
    occupation: "Chief Art Historian & Museum Curator",
    districtId: "tourist",
    locationId: "loc_metro_museum",
    locationName: "Metropolitan Museum of Art & History",
    avatarEmoji: "🏛️",
    avatarColor: "#d97706",
    personality: "Cultured, passionate, storytelling specialist, loves explaining symbolism in historical artwork.",
    speakingStyle: "Cultured, expressive British English, rich in descriptive adjectives.",
    accent: "British (Standard RP)",
    level: "B1",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Guiding an audio tour through the Renaissance oil painting gallery",
    greetingText: "Welcome to the Metropolitan Museum. Today we are exploring the revolutionary use of light in 17th-century landscape painting.",
    defaultTopics: ["Artwork Interpretation & Symbolism", "Museum Audio Guides & Exhibitions", "Historical Eras (Renaissance, Victorian, Modern)", "Art Terminology"],
    voicePitch: 0.95,
    voiceRate: 0.9,
    voiceGender: "female",
    interests: ["Art restoration", "Classical mythology", "Historical preservation"],
    goals: ["Make art history accessible and inspiring for language learners"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_metro_museum",
    preferredHangouts: ["loc_grand_hotel", "loc_grand_bookstore"],
    currentMood: "cheerful",
    vocabularyObjectives: ["exhibit", "sculpture", "masterpiece", "century", "curator", "audio guide"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 15,
        locationId: "loc_metro_museum",
        roomName: "Main Exhibition Hall & Audio Guide Desk",
        activityDescription: "Conducting guided art history walkthroughs",
        arabicActivity: "إجراء جولات إرشادية حول تاريخ الفن",
        dialogueTopic: "Discussing Art, Culture & Museum Exhibits",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // 11. OCEAN BEACHFRONT & PIER
  // ══════════════════════════════════════════════════════════════
  {
    id: "npc_sofia",
    name: "Sofia Cruz",
    age: 23,
    gender: "female",
    occupation: "Beachfront Cafe Manager & Environmental Volunteer",
    districtId: "beach",
    locationId: "loc_sunset_beach",
    locationName: "Sunset Ocean Boardwalk & Cafe",
    avatarEmoji: "🏄‍♀️",
    avatarColor: "#0ea5e9",
    personality: "Vibrant, friendly, eco-conscious, loves discussing ocean life, weather, and surf culture.",
    speakingStyle: "Breezy, natural Californian/Coastal conversational English, highly approachable.",
    accent: "American (West Coast Coastal)",
    level: "B1",
    relationshipScore: 25,
    relationshipTier: "Friend",
    memory: ["Blended a fresh dragonfruit smoothie for you after a long walk on the pier"],
    currentScheduleActivity: "Serving organic acai bowls on the sunlit boardwalk deck",
    greetingText: "Hey! Catching the sunset breeze? Perfect day for a mango smoothie or a walk along the pier!",
    defaultTopics: ["Ocean Activities & Surfing", "Coastal Weather & Sun Safety", "Smoothies & Healthy Eating", "Marine Conservation"],
    voicePitch: 1.1,
    voiceRate: 1.0,
    voiceGender: "female",
    interests: ["Surfing", "Marine biology", "Beach volleyball", "Eco-friendly living"],
    goals: ["Organize regular community beach clean-up days"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_sunset_beach",
    preferredHangouts: ["loc_surf_shack", "loc_sarah_cafe"],
    currentMood: "cheerful",
    vocabularyObjectives: ["refreshing", "sunscreen", "boardwalk", "scenic", "coastal", "smoothie"],
    schedule: [
      {
        timeOfDay: "afternoon",
        hour: 15,
        locationId: "loc_sunset_beach",
        roomName: "Seaside Refreshments Deck",
        activityDescription: "Taking orders on the outdoor boardwalk deck",
        arabicActivity: "تسجيل طلبات الزبائن على منصة الشاطئ الخشبية",
        dialogueTopic: "Ordering Smoothies & Discussing Beach Life",
      },
    ],
  },
  {
    id: "npc_surf_coach_kai",
    name: "Kai Tanaka",
    age: 27,
    gender: "male",
    occupation: "Head Surf Instructor & Water Safety Lead",
    districtId: "beach",
    locationId: "loc_surf_shack",
    locationName: "Azure Wave Surf & Water Sports",
    avatarEmoji: "🌊",
    avatarColor: "#06b6d4",
    personality: "Relaxed, encouraging, vigilant about ocean safety and rip currents.",
    speakingStyle: "Casual, enthusiastic surf English, clear explanations of tide charts and water conditions.",
    accent: "Hawaiian / American Coastal",
    level: "B1",
    relationshipScore: 20,
    relationshipTier: "Acquaintance",
    memory: [],
    currentScheduleActivity: "Checking the afternoon tide forecast and waxing beginner surfboards",
    greetingText: "Aloha! Waves are looking great today, about 3 to 4 feet! Ever tried surfing or paddleboarding?",
    defaultTopics: ["Surf Lessons for Beginners", "Tides & Rip Current Warnings", "Renting Wetsuits & Boards", "Ocean Safety Flags"],
    voicePitch: 0.98,
    voiceRate: 1.0,
    voiceGender: "male",
    interests: ["Big wave surfing", "Oceanography", "Acoustic guitar"],
    goals: ["Teach 500 new surfers safe ocean navigation this season"],
    homeLocationId: "loc_apartment",
    workplaceLocationId: "loc_surf_shack",
    preferredHangouts: ["loc_sunset_beach", "loc_oakwood_diner"],
    currentMood: "cheerful",
    vocabularyObjectives: ["high tide", "low tide", "rip current", "wetsuit", "leash", "swell"],
    schedule: [
      {
        timeOfDay: "morning",
        hour: 11,
        locationId: "loc_surf_shack",
        roomName: "Surf Rental & Safety Briefing Deck",
        activityDescription: "Renting boards and explaining tide warnings",
        arabicActivity: "تأجير ألواح التزلج وشرح تحذيرات المد والجزر",
        dialogueTopic: "Renting Surf Gear & Ocean Safety",
      },
    ],
  },
];
