import { VocabularyWord, DistrictId } from "../../types";

export interface EnvironmentalLearningObject {
  id: string;
  name: string;
  signText: string;
  districtId: DistrictId;
  category:
    | "transit"
    | "medical"
    | "store"
    | "academic"
    | "civic"
    | "road"
    | "hospitality"
    | "nature";
  icon: string;
  x: number; // Canvas coordinate (0-1000)
  y: number; // Canvas coordinate (0-1000)
  phoneticIpa: string;
  arabicTranslation: string;
  definition: string;
  practicalTip: string;
  arabicTip: string;
  exampleSentence: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1";
  vocabularyWord: VocabularyWord;
  quiz?: {
    question: string;
    arabicQuestion: string;
    options: string[];
    correctIndex: number;
    explanation: string;
  };
}

export const ENVIRONMENTAL_LEARNING_OBJECTS: EnvironmentalLearningObject[] = [
  // ── 1. Transportation Hub ──
  {
    id: "env_obj_bus_stop",
    name: "City Bus Stop Shelter",
    signText: "BUS STOP",
    districtId: "transportation",
    category: "transit",
    icon: "Bus",
    x: 240,
    y: 430,
    phoneticIpa: "/ˈbʌs ˌstɑːp/",
    arabicTranslation: "موقف الحافلات",
    definition: "A designated curbside place where buses stop for passengers to board or alight.",
    practicalTip: "Check the posted timetable to confirm bus line numbers and scheduled arrival times.",
    arabicTip: "كلمة Bus Stop تعني موقف الباص، وتجد فيها عادة خريطة الخطوط ومواعيد الوصول.",
    exampleSentence: "Passengers queue politely at the bus stop during morning rush hour.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_bus_stop",
      word: "bus stop",
      phonetic: "/ˈbʌs ˌstɑːp/",
      partOfSpeech: "noun",
      definition: "a place where buses regularly stop for passengers",
      arabicTranslation: "موقف الباص / الحافلة",
      example: "We waited at the bus stop for twenty minutes.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["transit", "transportation"],
    },
    quiz: {
      question: "What should you do when arriving at a bus stop?",
      arabicQuestion: "ماذا تفعل عادة عند وصولك لموقف الحافلات؟",
      options: ["Board immediately without checking the line", "Check the timetable and line number", "Park your private car", "Ask for a hotel key"],
      correctIndex: 1,
      explanation: "Checking the route schedule ensures you take the right bus direction.",
    },
  },
  {
    id: "env_obj_ticket_office",
    name: "Central Railway Ticket Office",
    signText: "TICKET OFFICE",
    districtId: "transportation",
    category: "transit",
    icon: "Train",
    x: 740,
    y: 430,
    phoneticIpa: "/ˈtɪk.ɪt ˌɑː.fɪs/",
    arabicTranslation: "مكتب التذاكر",
    definition: "A service counter or window where travelers purchase travel tickets, passes, or reservations.",
    practicalTip: "You can ask for a 'Single' (one-way) or 'Return' (round-trip) ticket.",
    arabicTip: "في بريطانيا يُستخدم مصطلح Single للتذكرة ذهاباً فقط و Return للذهاب والإياب.",
    exampleSentence: "I bought a monthly commuter pass at the railway ticket office.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_ticket_office",
      word: "ticket office",
      phonetic: "/ˈtɪk.ɪt ˌɑː.fɪs/",
      partOfSpeech: "noun",
      definition: "an office where tickets are sold for travel or entertainment",
      arabicTranslation: "مكتب بيع التذاكر",
      example: "Purchase your train tickets at the main ticket office.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["transit", "travel"],
    },
  },
  {
    id: "env_obj_departures_board",
    name: "Airport Flight Departures Board",
    signText: "DEPARTURES",
    districtId: "transportation",
    category: "transit",
    icon: "Plane",
    x: 320,
    y: 220,
    phoneticIpa: "/dɪˈpɑːr.tʃɚz/",
    arabicTranslation: "المغادرون / الرحلات المغادرة",
    definition: "An electronic information display showing flight departure times, gate assignments, and status.",
    practicalTip: "Status words include: On Time, Delayed, Boarding, Gate Open, and Departed.",
    arabicTip: "لوحة المغادرين تعرض بوابات الصعود وحالة الرحلة (في موعدها، متأخرة، صعود الطائرة).",
    exampleSentence: "Check the departures board to locate your departure gate.",
    level: "A2",
    vocabularyWord: {
      id: "v_env_departures",
      word: "departures",
      phonetic: "/dɪˈpɑːr.tʃɚz/",
      partOfSpeech: "noun",
      definition: "the area of an airport dealing with passengers who are leaving",
      arabicTranslation: "صالة المغادرة / المغادرون",
      example: "Proceed to Terminal 2 Departures for check-in.",
      level: "A2",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["airport", "travel"],
    },
  },

  // ── 2. Downtown City Center ──
  {
    id: "env_obj_atm",
    name: "Automated Teller Machine",
    signText: "ATM • CASH WITHDRAWAL",
    districtId: "downtown",
    category: "civic",
    icon: "CreditCard",
    x: 420,
    y: 380,
    phoneticIpa: "/ˌeɪ.tiːˈem/",
    arabicTranslation: "صراف آلي",
    definition: "An electronic banking outlet allowing customers to complete basic transactions without branch staff.",
    practicalTip: "Key commands: Insert Card, Enter PIN, Withdraw Cash, Balance Inquiry, Print Receipt.",
    arabicTip: "المصطلحات الشائعة في الصراف: Withdraw (سحب)، Deposit (إيداع)، PIN (الرمز السري).",
    exampleSentence: "She inserted her debit card into the ATM to withdraw sixty dollars.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_atm",
      word: "ATM",
      phonetic: "/ˌeɪ.tiːˈem/",
      partOfSpeech: "noun",
      definition: "automated teller machine for financial transactions",
      arabicTranslation: "صراف آلي",
      example: "I need to stop by an ATM to get some cash.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["banking", "money"],
    },
  },
  {
    id: "env_obj_crosswalk_dt",
    name: "Zebra Pedestrian Crosswalk",
    signText: "PEDESTRIAN CROSSING",
    districtId: "downtown",
    category: "road",
    icon: "Footprints",
    x: 400,
    y: 500,
    phoneticIpa: "/pəˈdes.tri.ən ˈkrɑː.sɪŋ/",
    arabicTranslation: "ممر المشاة",
    definition: "A marked part of a road where pedestrians have right of way to cross safely.",
    practicalTip: "In the UK, pedestrian crossings with flashing orange globes are called 'Zebra crossings'.",
    arabicTip: "ممر المشاة يعطي الأولوية للمشاة للعبور بأمان، انتبه لإشارة المشاة الخضراء.",
    exampleSentence: "Always look both ways before stepping onto the pedestrian crossing.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_crosswalk",
      word: "crosswalk",
      phonetic: "/ˈkrɑːs.wɑːk/",
      partOfSpeech: "noun",
      definition: "a marked path where pedestrians can cross a road safely",
      arabicTranslation: "ممر مشاة",
      example: "Cross the street at the designated crosswalk.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["traffic", "city"],
    },
  },

  // ── 3. Medical District (St. Jude) ──
  {
    id: "env_obj_emergency",
    name: "Hospital Emergency Entrance",
    signText: "EMERGENCY — AMBULANCE ONLY",
    districtId: "medical",
    category: "medical",
    icon: "HeartPulse",
    x: 420,
    y: 220,
    phoneticIpa: "/ɪˈmɜːrdʒənsi/",
    arabicTranslation: "قسم الطوارئ والإسعاف",
    definition: "A specialized hospital department offering immediate medical treatment for acute illness or trauma.",
    practicalTip: "Also abbreviated as the 'ER' in American English or 'A&E' (Accident & Emergency) in British English.",
    arabicTip: "يسمى قسم الطوارئ ER في أمريكا أو A&E في بريطانيا، وهو مخصص للحالات العاجلة.",
    exampleSentence: "The paramedics rushed the injured patient into the emergency room.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_emergency",
      word: "emergency",
      phonetic: "/ɪˈmɜːrdʒənsi/",
      partOfSpeech: "noun",
      definition: "a serious, unexpected, and often dangerous situation requiring immediate action",
      arabicTranslation: "حالة طارئة / طوارئ",
      example: "Call 911 immediately in case of an emergency.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["medical", "health"],
    },
    quiz: {
      question: "What is the British English equivalent of 'Emergency Room' (ER)?",
      arabicQuestion: "ما هو المصطلح البريطاني المقابل لقسم الطوارئ ER؟",
      options: ["A&E (Accident & Emergency)", "ICU (Intensive Care)", "Pharmacy Hub", "Waiting Salon"],
      correctIndex: 0,
      explanation: "In the UK, hospital emergency departments are known as A&E.",
    },
  },
  {
    id: "env_obj_pharmacy",
    name: "CareFirst Pharmacy Counter",
    signText: "PHARMACY • PRESCRIPTIONS",
    districtId: "medical",
    category: "medical",
    icon: "Pill",
    x: 740,
    y: 220,
    phoneticIpa: "/ˈfɑːr.mə.si/",
    arabicTranslation: "الصيدلية وصرف الأدوية",
    definition: "A licensed store where prescription medicines and healthcare remedies are dispensed.",
    practicalTip: "Also called a 'chemist' or 'drugstore'. You will need a 'prescription' from your doctor for certain medicines.",
    arabicTip: "تسمى الصيدلية أيضاً Chemist أو Drugstore، وتصرف الأدوية بوصفة طبية Prescription.",
    exampleSentence: "Hand your doctor's prescription to the pharmacist at the counter.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_pharmacy",
      word: "pharmacy",
      phonetic: "/ˈfɑːr.mə.si/",
      partOfSpeech: "noun",
      definition: "a shop or hospital dispensary where medicines are prepared and sold",
      arabicTranslation: "صيدلية",
      example: "The local pharmacy is open 24 hours a day.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["medical", "health"],
    },
  },

  // ── 4. Oxford University Campus ──
  {
    id: "env_obj_library",
    name: "Bodleian Campus Library",
    signText: "UNIVERSITY LIBRARY • SILENCE",
    districtId: "university",
    category: "academic",
    icon: "BookOpen",
    x: 320,
    y: 220,
    phoneticIpa: "/ˈlaɪ.brer.i/",
    arabicTranslation: "مكتبة الجامعة والبحث العلمي",
    definition: "A building containing collections of books, periodicals, and study spaces for reading and research.",
    practicalTip: "Key actions: 'Borrow' a book, 'Return' a book, 'Renew' a loan, 'Study carrel'.",
    arabicTip: "المصطلحات الجامعية في المكتبة: Borrow (استعارة)، Return (إرجاع)، Reference desk (مكتب المراجع).",
    exampleSentence: "Students reserve quiet study rooms inside the university library.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_library",
      word: "library",
      phonetic: "/ˈlaɪ.brer.i/",
      partOfSpeech: "noun",
      definition: "a building or room containing collections of books and resources",
      arabicTranslation: "مكتبة للقراءة والبحث",
      example: "I spent the afternoon studying at the university library.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["academic", "education"],
    },
  },
  {
    id: "env_obj_lecture_hall",
    name: "Amphitheater Lecture Hall",
    signText: "LECTURE HALL 101",
    districtId: "university",
    category: "academic",
    icon: "GraduationCap",
    x: 740,
    y: 220,
    phoneticIpa: "/ˈlek.tʃɚ ˌhɑːl/",
    arabicTranslation: "قاعة المحاضرات والندوات",
    definition: "A large tiered room used for instruction and educational presentations to university students.",
    practicalTip: "A 'lecture' is a formal talk given by a professor, while a 'seminar' is a small discussion class.",
    arabicTip: "المحاضرة Lecture تكون لقاعة كبيرة من الطلاب، بينما Seminar تكون حلقة نقاش صغيرة.",
    exampleSentence: "The professor delivered a fascinating lecture on modern economics.",
    level: "A2",
    vocabularyWord: {
      id: "v_env_lecture_hall",
      word: "lecture hall",
      phonetic: "/ˈlek.tʃɚ ˌhɑːl/",
      partOfSpeech: "noun",
      definition: "a large auditorium where university classes and lectures are held",
      arabicTranslation: "مدرج / قاعة محاضرات",
      example: "The guest speaker addressed hundreds in the main lecture hall.",
      level: "A2",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["academic", "education"],
    },
  },

  // ── 5. Shopping Promenade ──
  {
    id: "env_obj_supermarket",
    name: "SuperFresh Grocery Market",
    signText: "SUPERMARKET • FRESH PRODUCE",
    districtId: "shopping",
    category: "store",
    icon: "ShoppingBag",
    x: 320,
    y: 220,
    phoneticIpa: "/ˈsuː.pɚˌmɑːr.kɪt/",
    arabicTranslation: "سوبرماركت / متجر المواد الغذائية",
    definition: "A large self-service grocery store selling fresh foods, household goods, and beverages.",
    practicalTip: "Key retail terms: Shopping cart (trolley), Aisle, Checkout counter, Cashier, Receipt, Organic.",
    arabicTip: "في السوبرماركت: Aisle تعني ممر الأرفف، Checkout تعني صندوق الدفع، Receipt تعني الفاتورة.",
    exampleSentence: "Grab a shopping cart at the entrance before browsing the aisles.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_supermarket",
      word: "supermarket",
      phonetic: "/ˈsuː.pɚˌmɑːr.kɪt/",
      partOfSpeech: "noun",
      definition: "a large retail store selling groceries and household items",
      arabicTranslation: "سوبرماركت / بقالة كبرى",
      example: "Let's stop by the supermarket to buy fresh vegetables.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["shopping", "food"],
    },
  },

  // ── 6. Ocean Beachfront ──
  {
    id: "env_obj_lifeguard",
    name: "Coastal Lifeguard Station",
    signText: "LIFEGUARD ON DUTY • RESCUE",
    districtId: "beach",
    category: "nature",
    icon: "LifeBuoy",
    x: 680,
    y: 420,
    phoneticIpa: "/ˈlaɪf.ɡɑːrd/",
    arabicTranslation: "برج الإنقاذ البحري والمنقذ",
    definition: "A specialized observation post where trained rescue swimmers watch over bathers and enforce safety rules.",
    practicalTip: "Observe the warning flags: Green (safe), Yellow (caution/currents), Red (prohibited).",
    arabicTip: "المنقذ البحري Lifeguard يراقب الشاطئ ويرفع أعلام السلامة لتنبيه السباحين.",
    exampleSentence: "Always swim between the red and yellow flags where the lifeguard can see you.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_lifeguard_beach",
      word: "lifeguard",
      phonetic: "/ˈlaɪf.ɡɑːrd/",
      partOfSpeech: "noun",
      definition: "an expert swimmer employed to rescue swimmers in danger",
      arabicTranslation: "منقذ بحري",
      example: "The lifeguard blew her whistle to alert the swimmers.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["beach", "safety"],
    },
  },

  // ── 7. Heritage Tourist Quarter ──
  {
    id: "env_obj_hotel_reception",
    name: "Grand Horizon Hotel Lobby",
    signText: "HOTEL RECEPTION • CHECK-IN",
    districtId: "tourist",
    category: "hospitality",
    icon: "Key",
    x: 320,
    y: 220,
    phoneticIpa: "/rɪˈsep.ʃən/",
    arabicTranslation: "استقبال الفندق وتسجيل الوصول",
    definition: "The front desk area in a hotel where guests check in, check out, and receive room keys.",
    practicalTip: "Standard phrase: 'Hello, I have a reservation under the name [Your Name] for two nights.'",
    arabicTip: "عبارة الحجز في الفندق: 'I have a reservation under the name...' لتسجيل الدخول بسهولة.",
    exampleSentence: "The receptionist handed us two electronic keycards for room 402.",
    level: "A1",
    vocabularyWord: {
      id: "v_env_reception",
      word: "reception",
      phonetic: "/rɪˈsep.ʃən/",
      partOfSpeech: "noun",
      definition: "the front desk where visitors and guests are greeted and registered",
      arabicTranslation: "مكتب الاستقبال",
      example: "Please register your details at hotel reception.",
      level: "A1",
      mastery: 1,
      repetitions: 0,
      interval: 1,
      easeFactor: 2.5,
      lapses: 0,
      retentionEstimate: 0.85,
      nextReviewDate: new Date().toISOString(),
      timesReviewed: 0,
      tags: ["hotel", "travel"],
    },
  },
];
