import { CitySign } from "../../types";

export const ENVIRONMENTAL_SIGNS: CitySign[] = [
  // ── 1. Transportation Hub ──
  {
    id: "sign_airport_departure",
    text: "DEPARTURES — INTERNATIONAL TERMINAL B",
    subtext: "Please have your passport and boarding pass ready for security inspection.",
    arabicMeaning: "المغادرون — الصالة الدولية ب (يرجى تجهيز جواز السفر وبطاقة الصعود للتفتيش الأمني)",
    category: "airport_board",
    districtId: "transportation",
    locationId: "loc_airport",
    streetName: "Skyway Boulevard",
    cefrLevel: "A1",
    pronunciationIpa: "/dɪˈpɑːr.tʃɚz/",
    practicalTip: "Look for 'Departures' when leaving and 'Arrivals' when picking up incoming travelers.",
    arabicTip: "كلمة Departures تعني المغادرون أو الرحلات المغادرة، بينما Arrivals تعني القادمون.",
    vocabularyWords: [
      {
        id: "v_departure",
        word: "departure",
        phonetic: "/dɪˈpɑːr.tʃɚ/",
        partOfSpeech: "noun",
        definition: "the act of leaving a place, especially to start a journey",
        arabicTranslation: "مغادرة / إقلاع",
        example: "Our flight departure is scheduled for 10:30 AM.",
        level: "A1",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["airport", "travel"],
      },
      {
        id: "v_boarding_pass",
        word: "boarding pass",
        phonetic: "/ˈbɔːr.dɪŋ ˌpæs/",
        partOfSpeech: "noun",
        definition: "a card that gives you permission to get on a plane or ship",
        arabicTranslation: "بطاقة صعود الطائرة",
        example: "Please scan your boarding pass at the gate.",
        level: "A1",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["airport", "travel"],
      },
    ],
    comprehensionQuestion: {
      question: "What document should you hold ready according to this sign?",
      arabicQuestion: "ما هي الوثيقة التي يجب عليك تجهيزها وفقاً لهذه اللوحة؟",
      options: ["Hotel receipt", "Passport & Boarding Pass", "Driver's License", "Student ID"],
      correctIndex: 1,
      explanation: "The sign explicitly states: 'Please have your passport and boarding pass ready'.",
    },
  },
  {
    id: "sign_baggage_claim",
    text: "BAGGAGE CLAIM — CAROUSEL 3",
    subtext: "Oversized luggage and fragile items at Counter 4.",
    arabicMeaning: "استلام الأمتعة — السير رقم 3 (الأمتعة كبيرة الحجم عند مكتب 4)",
    category: "airport_board",
    districtId: "transportation",
    locationId: "loc_airport",
    streetName: "Skyway Boulevard",
    cefrLevel: "A2",
    pronunciationIpa: "/ˈbæɡ.ɪdʒ kleɪm/",
    practicalTip: "A 'carousel' is the rotating conveyor belt where suitcases arrive.",
    arabicTip: "كلمة Carousel تعني سير نقل الحقائب الدوار في صالة الوصول.",
    vocabularyWords: [
      {
        id: "v_baggage",
        word: "baggage",
        phonetic: "/ˈbæɡ.ɪdʒ/",
        partOfSpeech: "noun",
        definition: "all the bags and suitcases that you take when you travel",
        arabicTranslation: "أمتعة / حقائب سفر",
        example: "Collect your checked baggage at Carousel 3.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["airport", "travel"],
      },
      {
        id: "v_carousel",
        word: "carousel",
        phonetic: "/ˌkær.əˈsel/",
        partOfSpeech: "noun",
        definition: "a moving circular belt from which passengers collect luggage",
        arabicTranslation: "سير الأمتعة الدوار",
        example: "Wait by the carousel for your suitcases.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["airport", "travel"],
      },
    ],
    comprehensionQuestion: {
      question: "Where should oversized or fragile luggage be collected?",
      arabicQuestion: "أين يتم استلام الأمتعة الكبيرة أو القابلة للكسر؟",
      options: ["Carousel 1", "Counter 4", "Security Exit", "Terminal C"],
      correctIndex: 1,
      explanation: "Subtext specifies that oversized and fragile items must be picked up at Counter 4.",
    },
  },
  {
    id: "sign_subway_platform",
    text: "METRO BLUE LINE — DOWNTOWN & UNIVERSITY",
    subtext: "Stand behind the yellow line. Tap your transit smartcard before boarding.",
    arabicMeaning: "خط المترو الأزرق — وسط المدينة والجامعة (قف خلف الخط الأصفر، امسح بطاقتك الذكية قبل الركوب)",
    category: "transit",
    districtId: "transportation",
    locationId: "loc_subway",
    streetName: "Central Transit Plaza",
    cefrLevel: "A1",
    pronunciationIpa: "/ˈbluː laɪn/",
    practicalTip: "Always stand behind the textured yellow safety strip until the train stops completely.",
    arabicTip: "الوقوف خلف الخط الأصفر قاعدة أمان عالمية في جميع محطات المترو.",
    vocabularyWords: [
      {
        id: "v_platform",
        word: "platform",
        phonetic: "/ˈplæt.fɔːrm/",
        partOfSpeech: "noun",
        definition: "an area alongside a railway track where passengers get on and off trains",
        arabicTranslation: "رصيف المحطة / قطار الأنفاق",
        example: "The train for Downtown is arriving at Platform 2.",
        level: "A1",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["transit", "subway"],
      },
    ],
    comprehensionQuestion: {
      question: "What should passengers do before boarding the train?",
      arabicQuestion: "ماذا يجب على الركاب فعله قبل ركوب القطار؟",
      options: ["Show a passport", "Tap their transit smartcard", "Call a taxi", "Stand on the tracks"],
      correctIndex: 1,
      explanation: "The sign instructs passengers to tap their transit smartcard before boarding.",
    },
  },

  // ── 2. Downtown City Center ──
  {
    id: "sign_cafe_specials",
    text: "TODAY'S ARTISAN SPECIALS",
    subtext: "Oat Vanilla Latte + Warm Almond Croissant — $6.50 (Dairy-Free & Gluten-Free Options Available)",
    arabicMeaning: "عروض اليوم الخاصة بالمقهى: لاتيه الشوفان بالفانيليا + كرواسون اللوز الدافئ بـ 6.50$",
    category: "restaurant_menu",
    districtId: "downtown",
    locationId: "loc_cafe",
    streetName: "Broad Street",
    cefrLevel: "A1",
    pronunciationIpa: "/ˈɑːr.t̬ə.zən ˈspeʃ.əlz/",
    practicalTip: "'Dairy-free' means no cow milk (uses oat, almond, or soy milk instead).",
    arabicTip: "كلمة Dairy-free تعني خالٍ من مشتقات الألبان، مفيدة لمن يعانون من حساسية الحليب.",
    vocabularyWords: [
      {
        id: "v_dairy_free",
        word: "dairy-free",
        phonetic: "/ˈder.i friː/",
        partOfSpeech: "adjective",
        definition: "containing no milk products",
        arabicTranslation: "خالٍ من مشتقات الحليب والألبان",
        example: "Can I have a dairy-free iced cappuccino, please?",
        level: "A1",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["food", "cafe"],
      },
      {
        id: "v_croissant",
        word: "croissant",
        phonetic: "/kwɑːˈsɑːŋ/",
        partOfSpeech: "noun",
        definition: "a curved, flaky French pastry made of butter and yeast dough",
        arabicTranslation: "كرواسون (مخبوز فرنسي هش)",
        example: "I would like a warm butter croissant.",
        level: "A1",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["food", "cafe"],
      },
    ],
    comprehensionQuestion: {
      question: "What does 'dairy-free' indicate about the drink options?",
      arabicQuestion: "ماذا تعني عبارة 'dairy-free' حول خيارات المشروبات؟",
      options: ["Contains extra butter", "Free of cow milk products", "Contains extra sugar", "Served ice cold"],
      correctIndex: 1,
      explanation: "Dairy-free means the product contains no animal milk products.",
    },
  },
  {
    id: "sign_bank_atm",
    text: "24-HOUR MULTI-CURRENCY ATM",
    subtext: "Insert card chip-first. Protect your PIN. Foreign exchange rates updated hourly.",
    arabicMeaning: "صراف آلي متعدد العملات على مدار 24 ساعة (أدخل الشريحة أولاً، احمِ رقمك السري)",
    category: "safety",
    districtId: "downtown",
    locationId: "loc_bank",
    streetName: "Wall Street Promenade",
    cefrLevel: "A2",
    pronunciationIpa: "/ˌeɪ.tiːˈem/",
    practicalTip: "PIN stands for 'Personal Identification Number' (the secret 4 or 6-digit passcode).",
    arabicTip: "كلمة PIN ترمز إلى الرقم السري الخاص ببطاقتك المصرفية.",
    vocabularyWords: [
      {
        id: "v_atm",
        word: "ATM",
        phonetic: "/ˌeɪ.tiːˈem/",
        partOfSpeech: "noun",
        definition: "Automated Teller Machine; electronic device allowing cash withdrawals",
        arabicTranslation: "جهاز الصراف الآلي",
        example: "Is there an ATM nearby where I can withdraw cash?",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["finance", "bank"],
      },
    ],
  },
  {
    id: "sign_police_notice",
    text: "NEIGHBORHOOD POLICE SUBSTATION — COMMUNITY DESK",
    subtext: "Report lost property, minor civil inquiries, or non-emergency assistance here. In urgent emergencies dial 911.",
    arabicMeaning: "مخفر شرطة الحي — مكتب خدمة المجتمع (للإبلاغ عن المفقودات أو الاستفسارات، في الطوارئ اتصل بـ 911)",
    category: "safety",
    districtId: "downtown",
    locationId: "loc_police_station",
    streetName: "Broad Street",
    cefrLevel: "A2",
    pronunciationIpa: "/ˈsʌbˌsteɪ.ʃən/",
    practicalTip: "Use the local desk for lost wallets or non-emergencies; save 911 only for life-threatening emergencies.",
    vocabularyWords: [
      {
        id: "v_inquiry",
        word: "inquiry",
        phonetic: "/ɪnˈkwaɪ.ri/",
        partOfSpeech: "noun",
        definition: "an official question or request for information",
        arabicTranslation: "استفسار / سؤال رسمي",
        example: "I have an inquiry regarding my lost wallet.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["civic", "safety"],
      },
    ],
  },

  // ── 3. Residential District ──
  {
    id: "sign_residential_rules",
    text: "MAPLE GROVE RESIDENTS: RECYCLING & QUIET HOURS",
    subtext: "Quiet hours observed from 10:00 PM to 7:00 AM daily. Please sort recyclables into blue bins.",
    arabicMeaning: "سكان مابل جروف: قواعد إعادة التدوير وساعات الهدوء (الهدوء من 10 مساءً حتى 7 صباحاً، فرز النفايات في الحاويات الزرقاء)",
    category: "civic_direction",
    districtId: "residential",
    locationId: "loc_apartment",
    streetName: "Elm Street",
    cefrLevel: "A2",
    pronunciationIpa: "/ˈkwaɪ.ət ˈaʊ.ɚz/",
    practicalTip: "'Quiet hours' means avoiding loud music, vacuuming, or noisy gatherings during late night hours.",
    arabicTip: "ساعات الهدوء Quiet hours قانون سكني معتمد لحماية راحة الجيران.",
    vocabularyWords: [
      {
        id: "v_recyclables",
        word: "recyclables",
        phonetic: "/ˌriːˈsaɪ.klə.bəlz/",
        partOfSpeech: "noun",
        definition: "materials (paper, plastic, glass) that can be processed and reused",
        arabicTranslation: "المواد القابلة للتدوير",
        example: "Place clean plastic bottles into the recyclables bin.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["residential", "environment"],
      },
    ],
  },

  // ── 4. Shopping & Promenade ──
  {
    id: "sign_store_return_policy",
    text: "METRO BOUTIQUE — 30-DAY RETURN POLICY",
    subtext: "Full refund with original receipt and price tags attached. Final sale items excluded.",
    arabicMeaning: "متجر مترو: سياسة الإرجاع خلال 30 يوماً (استرداد كامل مع الفاتورة والبطاقات الأصلية)",
    category: "store_promo",
    districtId: "shopping",
    locationId: "loc_fashion",
    streetName: "Promenade High Street",
    cefrLevel: "A2",
    pronunciationIpa: "/rɪˈfʌnd/",
    practicalTip: "'Final sale' means the item cannot be returned or exchanged under any circumstance.",
    arabicTip: "عبارة Final sale تعني أن السلعة مباعة نهائياً ولا تقبل الإرجاع أو الاستبدال.",
    vocabularyWords: [
      {
        id: "v_receipt",
        word: "receipt",
        phonetic: "/rɪˈsiːt/",
        partOfSpeech: "noun",
        definition: "a printed slip of paper showing that you have paid for goods or services",
        arabicTranslation: "إيصال دفع / فاتورة الشراء",
        example: "Please keep your receipt in case you want to return the sweater.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["shopping", "retail"],
      },
      {
        id: "v_refund",
        word: "refund",
        phonetic: "/ˈriː.fʌnd/",
        partOfSpeech: "noun",
        definition: "an amount of money that is given back to you if you return goods",
        arabicTranslation: "استرداد المبلغ المدفوع",
        example: "The cashier processed a full refund to my credit card.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["shopping", "retail"],
      },
    ],
  },
  {
    id: "sign_supermarket_organic",
    text: "SUPERFRESH: 100% LOCALLY SOURCED ORGANIC PRODUCE",
    subtext: "Pesticide-free farm harvest. Certified non-GMO. Scan barcode with loyalty app for 15% discount.",
    arabicMeaning: "سوبر فريش: خضار وفواكه عضوية محلية 100% (خالية من المبيدات، غير معدلة وراثياً، خصم 15% مع التطبيق)",
    category: "store_promo",
    districtId: "shopping",
    locationId: "loc_superfresh_market",
    streetName: "Market Row",
    cefrLevel: "B1",
    pronunciationIpa: "/ɔːrˈɡæn.ɪk ˈproʊ.duːs/",
    practicalTip: "'Produce' as a noun refers to fresh agricultural fruits and vegetables.",
    vocabularyWords: [
      {
        id: "v_produce",
        word: "produce",
        phonetic: "/ˈproʊ.duːs/",
        partOfSpeech: "noun",
        definition: "fresh fruits and vegetables grown on a farm",
        arabicTranslation: "المحاصيل الطازجة / الخضار والفواكه",
        example: "The organic produce section is located on the right.",
        level: "B1",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["food", "groceries"],
      },
    ],
  },

  // ── 5. Innovation & Tech Plaza ──
  {
    id: "sign_tech_visitor_policy",
    text: "NEXUS INNOVATIONS HQ — VISITOR & SECURITY PROTOCOL",
    subtext: "All guests must sign non-disclosure agreements (NDA) and wear digital guest badges at all times.",
    arabicMeaning: "المقر الرئيسي لنكسس: بروتوكول الزوار والأمن (توقيع اتفاقية السرية وارتداء بطاقة الزائر طوال الوقت)",
    category: "civic_direction",
    districtId: "business",
    locationId: "loc_tech_office",
    streetName: "Silicon Avenue",
    cefrLevel: "B2",
    pronunciationIpa: "/ˌprəʊ.tə.kɒl/",
    practicalTip: "An 'NDA' (Non-Disclosure Agreement) is a legal agreement to keep proprietary business ideas confidential.",
    vocabularyWords: [
      {
        id: "v_nda",
        word: "non-disclosure agreement",
        phonetic: "/ˌnɒn.dɪˈskləʊ.ʒər əˈɡriː.mənt/",
        partOfSpeech: "noun",
        definition: "a legal contract where parties agree not to disclose confidential information",
        arabicTranslation: "اتفاقية عدم الإفصاح والسرية",
        example: "Please sign the non-disclosure agreement before entering the AI lab.",
        level: "B2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["tech", "business", "legal"],
      },
    ],
  },

  // ── 6. Oxford University Campus ──
  {
    id: "sign_library_quiet",
    text: "SILENT RESEARCH STACKS — NO CELL PHONES OR CONVERSATIONS",
    subtext: "Laptops must remain muted. Group discussion rooms available on Floor 1.",
    arabicMeaning: "قاعة الأبحاث الصامتة — يُمنع استخدام الهواتف أو التحدث (كتم صوت الحواسب، تتوفر قاعات النقاش الجماعي في الطابق الأول)",
    category: "campus_announcement",
    districtId: "university",
    locationId: "loc_library",
    streetName: "Scholars Walk",
    cefrLevel: "B1",
    pronunciationIpa: "/ˈsaɪ.lənt/",
    practicalTip: "'Stacks' refers to the towering multi-level bookshelf sections in traditional academic libraries.",
    arabicTip: "كلمة Stacks في الجامعات تشير إلى أروقة رفوف الكتب والأرشيف الأكاديمي.",
    vocabularyWords: [
      {
        id: "v_stacks",
        word: "stacks",
        phonetic: "/stæks/",
        partOfSpeech: "noun",
        definition: "the main bookshelves in a library, especially those closed to non-researchers",
        arabicTranslation: "رفوف المكتبة / أرشيف الكتب",
        example: "The rare linguistic manuscripts are located in the east stacks.",
        level: "B1",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["university", "academic"],
      },
    ],
  },
  {
    id: "sign_academic_debate",
    text: "OXFORD UNION: ANNUAL INTER-COLLEGIATE DEBATE TOURNAMENT",
    subtext: "Topic: 'Resolved: Artificial Intelligence Requires Global Multilateral Governance'. Open to all matriculated scholars.",
    arabicMeaning: "اتحاد أكسفورد: مناظرة الجامعات السنوية (الموضوع: الذكاء الاصطناعي يتطلب حوكمة دولية، مفتوحة لجميع الطلاب)",
    category: "campus_announcement",
    districtId: "university",
    locationId: "loc_library",
    streetName: "Scholars Walk",
    cefrLevel: "C1",
    pronunciationIpa: "/dɪˈbeɪt ˈtʊr.nə.mənt/",
    practicalTip: "A formal debate motion begins with 'Resolved: ...' defining the central proposition being argued.",
    vocabularyWords: [
      {
        id: "v_governance",
        word: "governance",
        phonetic: "/ˈɡʌv.ɚ.nəns/",
        partOfSpeech: "noun",
        definition: "the way that organizations or countries are managed and governed at the highest level",
        arabicTranslation: "حوكمة / إدارة تنظيمية عليا",
        example: "Effective multilateral governance prevents regulatory fragmentation.",
        level: "C1",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["academic", "debate", "advanced"],
      },
    ],
  },

  // ── 7. St. Jude Medical Center ──
  {
    id: "sign_hospital_triage",
    text: "EMERGENCY TRIAGE & INTAKE — CHECK-IN PROTOCOL",
    subtext: "Patients categorized by clinical severity. Please sanitize hands and report fever symptoms immediately.",
    arabicMeaning: "الفرز الطبي وحالات الطوارئ (يتم تصنيف المرضى حسب الخطورة السريرية، يرجى تعقيم اليدين والإبلاغ عن أعراض الحمى فوراً)",
    category: "hospital_notice",
    districtId: "medical",
    locationId: "loc_hospital",
    streetName: "Health Avenue",
    cefrLevel: "A2",
    pronunciationIpa: "/ˈtriː.ɑːʒ/",
    practicalTip: "'Triage' means prioritizing medical treatment according to the urgency of their condition.",
    arabicTip: "الفرز الطبي Triage يضمن علاج الحالات الأكثر خطورة أولاً.",
    vocabularyWords: [
      {
        id: "v_triage",
        word: "triage",
        phonetic: "/ˈtriː.ɑːʒ/",
        partOfSpeech: "noun",
        definition: "the process of quickly examining sick or injured people to decide who needs treatment first",
        arabicTranslation: "الفرز الطبي / تصنيف الحالات الطارئة",
        example: "The nurse performed immediate triage in the emergency room.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["medical", "health"],
      },
      {
        id: "v_symptoms",
        word: "symptoms",
        phonetic: "/ˈsɪmp.təmz/",
        partOfSpeech: "noun",
        definition: "physical or mental features indicating a condition of disease",
        arabicTranslation: "أعراض المرض",
        example: "Please describe any fever or cough symptoms to the doctor.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["medical", "health"],
      },
    ],
  },

  // ── 8. Starlight Entertainment ──
  {
    id: "sign_gym_rules",
    text: "IRONFIT ATHLETIC CLUB — FLOOR ETIQUETTE",
    subtext: "Rerack all dumbbells after use. Wipe down machines with disinfectant spray. Athletic footwear required.",
    arabicMeaning: "نادي آيرون فيت الرياضي: آداب الصالة (إعادة الأوزان إلى أماكنها، مسح الأجهزة بالمعقم، ارتداء حذاء رياضي)",
    category: "safety",
    districtId: "entertainment",
    locationId: "loc_gym",
    streetName: "Broadway Walk",
    cefrLevel: "A2",
    pronunciationIpa: "/ˈetɪket/",
    practicalTip: "'Rerack' means returning free weights back to their numbered slots on the rack.",
    vocabularyWords: [
      {
        id: "v_disinfectant",
        word: "disinfectant",
        phonetic: "/ˌdɪs.ɪnˈfek.tənt/",
        partOfSpeech: "noun",
        definition: "a substance that kills bacteria and germs",
        arabicTranslation: "مادة مطهرة ومعقمة",
        example: "Spray disinfectant on the treadmill handlebars after your workout.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["fitness", "health"],
      },
    ],
  },

  // ── 10. Heritage & Tourist Quarter ──
  {
    id: "sign_hotel_concierge",
    text: "GRAND HORIZON CONCIERGE & GUEST AMENITIES",
    subtext: "Complimentary high-speed Wi-Fi: 'GrandHorizon_Guest'. Breakfast served 6:30 AM – 10:30 AM in the Crown Dining Salon.",
    arabicMeaning: "كونسيرج فندق جراند هورايزون (واي فاي مجاني للنزلاء، وجبة الإفطار من 6:30 إلى 10:30 صباحاً)",
    category: "cultural_plaque",
    districtId: "tourist",
    locationId: "loc_hotel",
    streetName: "Heritage Way",
    cefrLevel: "A2",
    pronunciationIpa: "/ˌkɒn.siˈeəʒ/",
    practicalTip: "'Complimentary' means provided free of charge by the hotel.",
    arabicTip: "كلمة Complimentary في الفنادق تعني مجاني أو على حساب الفندق.",
    vocabularyWords: [
      {
        id: "v_complimentary",
        word: "complimentary",
        phonetic: "/ˌkɒm.plɪˈmen.tər.i/",
        partOfSpeech: "adjective",
        definition: "given or supplied free of charge as a favor or courtesy",
        arabicTranslation: "مجاني / مقدم كضيافة",
        example: "Enjoy a complimentary morning espresso in the lobby lounge.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["hotel", "hospitality"],
      },
    ],
  },

  // ── 11. Ocean Beachfront ──
  {
    id: "sign_beach_lifeguard",
    text: "COASTAL LIFEGUARD NOTICE: FLAG WARNING SYSTEM",
    subtext: "Green Flag: Calm water. Yellow Flag: Caution / Moderate rip currents. Red Flag: Hazardous surf — no swimming permitted.",
    arabicMeaning: "تحذير الإنقاذ البحري: نظام الأعلام (الأخضر: مياه هادئة، الأصفر: حذر من التيارات، الأحمر: أمواج خطيرة وممنوع السباحة)",
    category: "safety",
    districtId: "beach",
    locationId: "loc_beachfront",
    streetName: "Coastal Boardwalk",
    cefrLevel: "A1",
    pronunciationIpa: "/ˈlaɪf.ɡɑːrd/",
    practicalTip: "Always verify the flag color at the lifeguard tower before entering ocean waves.",
    arabicTip: "الأعلام على الشواطئ تدل على درجة أمان السباحة (الأخضر آمن، الأصفر حذر، الأحمر ممنوع).",
    vocabularyWords: [
      {
        id: "v_lifeguard",
        word: "lifeguard",
        phonetic: "/ˈlaɪf.ɡɑːrd/",
        partOfSpeech: "noun",
        definition: "an expert swimmer employed to rescue bathers who get into difficulty",
        arabicTranslation: "منقذ بحري / سباح إنقاذ",
        example: "Always follow instructions given by the on-duty lifeguard.",
        level: "A1",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["beach", "safety"],
      },
      {
        id: "v_undercurrent",
        word: "rip current",
        phonetic: "/ˈrɪp ˌkɝː.ənt/",
        partOfSpeech: "noun",
        definition: "a strong, narrow surface current that flows seaward through the surf zone",
        arabicTranslation: "تيار سحب بحري قوي",
        example: "Swim parallel to the shoreline to escape a rip current.",
        level: "A2",
        mastery: 1,
        repetitions: 0,
        interval: 1,
        easeFactor: 2.5,
        lapses: 0,
        retentionEstimate: 0.8,
        nextReviewDate: new Date().toISOString(),
        timesReviewed: 0,
        tags: ["beach", "safety"],
      },
    ],
  },
];
