import { CityEvent } from "../../types";

export const CITY_EVENTS: CityEvent[] = [
  // ── 1. Downtown & Cafe Events ──
  {
    id: "ev_tourist_lost_wallet",
    title: "Lost Wallet on Broad Street",
    arabicTitle: "محفظة مفقودة في شارع برود",
    category: "lost_item",
    districtId: "downtown",
    locationId: "loc_sarah_cafe",
    streetName: "Market Square Boulevard",
    severity: "medium",
    activeTimeOfDay: ["morning", "afternoon"],
    description: "A frantic international visitor left their brown leather wallet near the cafe counter. Help them contact the barista or describe where it was left.",
    arabicDescription: "زائر أجنبي قلق نسي محفظته الجلدية البنية قرب طاولة المقهى. ساعده في التحدث مع الباريستا أو وصف مكانها.",
    cefrLevel: "A2",
    situationPrompt: "Visitor: 'Excuse me! I think I dropped my brown leather wallet near the counter 10 minutes ago. Did anyone hand it in?'",
    sampleAnswers: [
      {
        level: "A1",
        text: "Please ask the barista inside the cafe.",
        explanation: "Basic direct assistance",
      },
      {
        level: "A2",
        text: "Let's check with the barista at the counter. What does it look like?",
        explanation: "Polite inquiry and cooperative phrasing",
      },
      {
        level: "B1",
        text: "Don't worry, I can help you speak with the cafe manager to check their lost and found box.",
        explanation: "Empathetic communication with specific vocabulary (lost and found)",
      },
      {
        level: "B2",
        text: "Let's approach the staff right away. If it hasn't turned up, we should file a quick report at the local police substation around the corner.",
        explanation: "Complex conditional framing and advanced civic terminology",
      },
    ],
    rewardXp: 150,
    rewardCoins: 60,
    completed: false,
  },
  {
    id: "ev_street_musician",
    title: "Acoustic Jazz Busker on Market Square",
    arabicTitle: "عازف جاز في ساحة السوق",
    category: "street_busker",
    districtId: "downtown",
    locationId: "loc_sarah_cafe",
    streetName: "Market Square Boulevard",
    severity: "casual",
    activeTimeOfDay: ["afternoon", "evening"],
    description: "A talented street saxophonist is taking song requests and chatting with the crowd about the history of jazz standards.",
    arabicDescription: "عازف ساكسفون يعزف مقطوعات كلاسيكية ويطلب من الجمهور اقتراح أغانٍ والحديث عن تاريخ موسيقى الجاز.",
    cefrLevel: "B1",
    situationPrompt: "Musician: 'Hey folks! Thanks for stopping by. What style of music brings a smile to your face today?'",
    sampleAnswers: [
      {
        level: "A1",
        text: "I like slow jazz music, please.",
        explanation: "Simple preference",
      },
      {
        level: "A2",
        text: "Could you play something upbeat with a nice rhythm?",
        explanation: "Polite request with musical adjectives",
      },
      {
        level: "B1",
        text: "I really enjoy soulful blues ballads. Do you know any classic George Gershwin tunes?",
        explanation: "Genre-specific terms and composer reference",
      },
      {
        level: "B2",
        text: "Your improvisational phrasing is wonderful. Could you treat us to an upbeat bebop standard with syncopated rhythms?",
        explanation: "High-level musical vocabulary and articulate appreciation",
      },
    ],
    rewardXp: 120,
    rewardCoins: 40,
    completed: false,
  },

  // ── 2. Transportation Events ──
  {
    id: "ev_flight_delay_inquiry",
    title: "Flight Delay & Gate Reassignment",
    arabicTitle: "تأخر الرحلة وتغيير بوابة الصعود",
    category: "transit_delay",
    districtId: "transportation",
    locationId: "loc_airport_arrival",
    streetName: "Skyway Boulevard",
    severity: "urgent",
    activeTimeOfDay: ["morning", "afternoon", "night"],
    description: "A flight announcement reports a gate change from Gate 14 to Gate 22B due to maintenance. An elderly passenger looks confused.",
    arabicDescription: "إعلان بالمطار عن تغيير بوابة الصعود من 14 إلى 22B بسبب الصيانة. مسافر مسن يبدو تائهاً ويحتاج للمساعدة.",
    cefrLevel: "A2",
    situationPrompt: "Passenger: 'Oh dear, did that loudspeaker announcement say Gate 14 was cancelled? Where are we supposed to go now?'",
    sampleAnswers: [
      {
        level: "A1",
        text: "No, the flight is at Gate 22B now.",
        explanation: "Direct clarification",
      },
      {
        level: "A2",
        text: "They changed the gate to 22B. We should walk down the corridor to the right.",
        explanation: "Clear location update with directions",
      },
      {
        level: "B1",
        text: "The flight isn't cancelled, but due to maintenance, boarding has been moved to Gate 22B at the end of Concourse B.",
        explanation: "Reassuring reason and accurate airport terminology",
      },
      {
        level: "B2",
        text: "Don't worry, the flight is just delayed by twenty minutes for routine maintenance. Let me walk with you towards Gate 22B so we don't miss final boarding.",
        explanation: "Empathetic, clear, and proactive assistance",
      },
    ],
    rewardXp: 180,
    rewardCoins: 75,
    completed: false,
  },
  {
    id: "ev_subway_card_assist",
    title: "Subway Ticket Kiosk Malfunction",
    arabicTitle: "مساعدة في جهاز تذاكر المترو",
    category: "transit_delay",
    districtId: "transportation",
    locationId: "loc_subway_central",
    streetName: "Metro Plaza Way",
    severity: "casual",
    activeTimeOfDay: ["morning", "evening"],
    description: "A tourist's credit card was rejected at the automated fare machine. Guide them to the station attendant counter.",
    arabicDescription: "بطاقة سائح لم تُقبل في جهاز التذاكر الآلي. أرشده إلى شباك موظف المحطة.",
    cefrLevel: "A1",
    situationPrompt: "Commuter: 'Excuse me! The machine keeps beeping red when I insert my card. How can I buy a single-ride pass?'",
    sampleAnswers: [
      {
        level: "A1",
        text: "You can pay with cash over there at the window.",
        explanation: "Basic direction",
      },
      {
        level: "A2",
        text: "The card reader might be offline. You can talk to Station Master Brian at the information booth.",
        explanation: "Helpful troubleshooting with named NPC reference",
      },
      {
        level: "B1",
        text: "This terminal only accepts contactless payment. If you have cash or need an Oyster-style MetroCard, the manned ticket office is just across the concourse.",
        explanation: "Specific technical details and clear options",
      },
    ],
    rewardXp: 130,
    rewardCoins: 45,
    completed: false,
  },

  // ── 3. Medical Events ──
  {
    id: "ev_pharmacy_allergy_warning",
    title: "Prescription Allergy Clarification",
    arabicTitle: "توضيح حساسية الدواء في الصيدلية",
    category: "medical_inquiry",
    districtId: "medical",
    locationId: "loc_stjude_hospital",
    streetName: "Florence Nightingale Way",
    severity: "urgent",
    activeTimeOfDay: ["morning", "afternoon"],
    description: "A patient forgot to mention their penicillin allergy when receiving their antibiotic prescription.",
    arabicDescription: "مريض نسي ذكر حساسيته من البنسلين عند استلام المضاد الحيوي. ساعده في إبلاغ الصيدلانية فوراً.",
    cefrLevel: "A2",
    situationPrompt: "Pharmacist: 'Here is your Amoxicillin prescription. Take one capsule twice daily after meals.'",
    sampleAnswers: [
      {
        level: "A1",
        text: "Wait! I have an allergy to penicillin!",
        explanation: "Urgent basic safety statement",
      },
      {
        level: "A2",
        text: "Excuse me, doctor, I forgot to say I am allergic to penicillin. Is this medication safe for me?",
        explanation: "Clear polite question regarding allergy risk",
      },
      {
        level: "B1",
        text: "Hold on please—Amoxicillin is in the penicillin family, right? I have a severe penicillin allergy, so could we substitute an alternative antibiotic?",
        explanation: "Informed medical question with substitution request",
      },
      {
        level: "B2",
        text: "Pardon the interruption, but my medical intake record might not show my severe adverse reaction to penicillin-based compounds. Could you consult with Dr. Hayes to prescribe a non-beta-lactam alternative?",
        explanation: "Clinical vocabulary, high precision and safety awareness",
      },
    ],
    rewardXp: 200,
    rewardCoins: 90,
    completed: false,
  },

  // ── 4. Innovation & Business Events ──
  {
    id: "ev_tech_pitch_emergency",
    title: "Startup Pitch Deck Formatting Crisis",
    arabicTitle: "أزمة تنسيق العرض التقديمي للشركة الناشئة",
    category: "business_challenge",
    districtId: "business",
    locationId: "loc_synergy_coworking",
    streetName: "Innovation Boulevard",
    severity: "urgent",
    activeTimeOfDay: ["afternoon"],
    description: "Zack is presenting to venture capitalists in 15 minutes, but needs help simplifying the slide on 'Customer Acquisition Cost vs Lifetime Value'.",
    arabicDescription: "زاك سيقدم عرضه للمستثمرين بعد 15 دقيقة ويحتاج لمساعدتك في تبسيط شريحة تكلفة اكتساب العملاء.",
    cefrLevel: "B1",
    situationPrompt: "Zack: 'Our CAC is $45 and LTV is $280, but investors get bored if I read numbers. How should I summarize this value proposition in one sentence?'",
    sampleAnswers: [
      {
        level: "B1",
        text: "You can say: 'Our customer value is more than six times higher than the acquisition cost.'",
        explanation: "Clear mathematical comparison in conversational English",
      },
      {
        level: "B2",
        text: "Tell them: 'We achieve strong unit economics with a 6-to-1 Lifetime Value to Acquisition ratio, proving scalable capital efficiency.'",
        explanation: "Executive business metrics and financial precision",
      },
    ],
    rewardXp: 220,
    rewardCoins: 100,
    completed: false,
  },

  // ── 5. Oxford University Events ──
  {
    id: "ev_oxford_debate_rebuttal",
    title: "Humanities Debate: Tech in Education",
    arabicTitle: "مناظرة أكسفورد: التكنولوجيا في التعليم",
    category: "academic_debate",
    districtId: "university",
    locationId: "loc_oxford_hall",
    streetName: "Chancellor's Way",
    severity: "medium",
    activeTimeOfDay: ["afternoon", "evening"],
    description: "Professor Holloway invites audience participation on whether AI replaces or enhances human tutors.",
    arabicDescription: "البروفيسور هولواي يدعو الحضور للمشاركة في مناظرة حول ما إذا كان الذكاء الاصطناعي يحل محل المعلم البشري أم يعززه.",
    cefrLevel: "B2",
    situationPrompt: "Prof. Holloway: 'The floor is open. How do you respond to the claim that automated tutors diminish human empathy in pedagogy?'",
    sampleAnswers: [
      {
        level: "B1",
        text: "I believe AI helps students practice anytime, but human teachers are still needed for encouragement and motivation.",
        explanation: "Balanced opinion with supporting reasons",
      },
      {
        level: "B2",
        text: "While automated platforms excel at adaptive drill repetition, they lack the emotional intelligence and cultural nuance required to foster genuine critical inquiry.",
        explanation: "Sophisticated rhetorical contrast and educational terminology",
      },
    ],
    rewardXp: 250,
    rewardCoins: 120,
    completed: false,
  },

  // ── 6. Greenfield Suburbs Events ──
  {
    id: "ev_suburb_bake_sale",
    title: "School Library Charity Book Sale",
    arabicTitle: "سوق خيري لكتب مكتبة المدرسة بالضواحي",
    category: "community_event",
    districtId: "suburbs",
    locationId: "loc_greenfield_school",
    streetName: "Meadowbrook Crescent",
    severity: "casual",
    activeTimeOfDay: ["morning", "afternoon"],
    description: "Hannah is hosting a charity book and pastry stall to buy new tablets for the elementary school library.",
    arabicDescription: "المعلمة هانا تنظم طاولة لبيع الكتب والمخبوزات الخيرية لشراء أجهزة لوحية لمكتبة المدرسة.",
    cefrLevel: "A1",
    situationPrompt: "Hannah: 'Welcome to our school charity fair! Would you like a homemade blueberry muffin with your mystery book bundle?'",
    sampleAnswers: [
      {
        level: "A1",
        text: "Yes please! How much are the muffin and books?",
        explanation: "Polite basic transaction",
      },
      {
        level: "A2",
        text: "That sounds delicious! I would love a muffin and a set of children's storybooks for the charity.",
        explanation: "Warm community interaction with quantities",
      },
      {
        level: "B1",
        text: "I'd be delighted to support the library initiative. Here is a donation, and I'll take a muffin and two mystery novels.",
        explanation: "Supportive civic tone and natural vocabulary",
      },
    ],
    rewardXp: 140,
    rewardCoins: 50,
    completed: false,
  },

  // ── 7. Ocean Beachfront Events ──
  {
    id: "ev_beach_rip_current_alert",
    title: "Ocean Red Flag & Rip Current Warning",
    arabicTitle: "تحذير الراية الحمراء والتيارات البحرية الساحبة",
    category: "safety_alert",
    districtId: "beach",
    locationId: "loc_surf_shack",
    streetName: "Ocean Pacific Boardwalk",
    severity: "urgent",
    activeTimeOfDay: ["afternoon"],
    description: "Lifeguard Jake raised the double red flags due to dangerous undertow. Two swimmers are walking toward the water with boogie boards.",
    arabicDescription: "رفع المنقذ الراية الحمراء المزدوجة بسبب التيارات البحرية الخطرة. اثنان من السباحين يتوجهان للبحر دون الانتباه للتحذير.",
    cefrLevel: "A2",
    situationPrompt: "Swimmer: 'Hey, looks like great waves today! Let's jump in right near the pier!'",
    sampleAnswers: [
      {
        level: "A1",
        text: "Stop! The red flags mean swimming is not allowed now!",
        explanation: "Direct urgent warning",
      },
      {
        level: "A2",
        text: "Excuse me! The lifeguards just posted red flags because of dangerous rip currents. It's unsafe to swim here today.",
        explanation: "Clear polite warning with official reasoning",
      },
      {
        level: "B1",
        text: "Be careful! Double red flags indicate hazardous undertows and strong rip currents near the pier pylons. Swimmers are prohibited from entering the water.",
        explanation: "Precise nautical safety terms and hazard identification",
      },
    ],
    rewardXp: 190,
    rewardCoins: 80,
    completed: false,
  },

  // ── 8. Heritage Tourist Quarter Events ──
  {
    id: "ev_hotel_room_upgrade",
    title: "Special Anniversary Room Upgrade Request",
    arabicTitle: "طلب ترقية غرفة بمناسبة ذكرى خاصة في الفندق",
    category: "hospitality_negotiation",
    districtId: "tourist",
    locationId: "loc_grand_hotel",
    streetName: "Royal Heritage Mile",
    severity: "medium",
    activeTimeOfDay: ["afternoon", "evening"],
    description: "Elena at the front desk asks if there is any special occasion for your stay in English City.",
    arabicDescription: "إيلينا في مكتب الاستقبال تسأل عما إذا كانت هناك مناسبة خاصة لإقامتك في فندق هورايزون.",
    cefrLevel: "B1",
    situationPrompt: "Elena: 'Welcome to The Grand Horizon. I see your reservation is for a Deluxe King. Are you celebrating anything special during your visit?'",
    sampleAnswers: [
      {
        level: "A2",
        text: "Yes, it is my graduation anniversary! Is a room on a higher floor possible?",
        explanation: "Polite request stating the celebration",
      },
      {
        level: "B1",
        text: "Actually, yes! We are celebrating my graduation. If there are any complimentary upgrades or rooms with a courtyard view available, we would deeply appreciate it.",
        explanation: "Diplomatic phrasing with hospitality vocabulary (complimentary upgrade, courtyard view)",
      },
      {
        level: "B2",
        text: "Indeed, we're celebrating a major academic milestone. Would it be at all possible to explore an upgrade to an executive suite, or perhaps a room with an unobstructed view of the historic monuments?",
        explanation: "Polite subjunctive framing and refined hospitality register",
      },
    ],
    rewardXp: 210,
    rewardCoins: 95,
    completed: false,
  },
];
